Sekachev/add projects structure
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #1
Opened 2022-09-10 13:23 UTC by cement-hools

2022-09-10 20:56 UTC, AntonZelinsky requested changes

2022-09-10 20:56 UTC, AntonZelinsky commented on Dockerfile
> +COPY ./requirements.txt .
Нет смысла два раза копировать этот файл, сразу копируй всё содержимое
```suggestion
COPY . .
```

2022-09-10 20:56 UTC, AntonZelinsky commented on Dockerfile
> +WORKDIR  /code
Я предпочитаю папку в докере называть именем проекта и большими буквами. Когда подклчюаешься внутрь контейнера, намного проще найти её, так как в коре много папок и у всех похоие имена

2022-09-10 20:56 UTC, AntonZelinsky commented on docker-compose.yaml
> +    container_name: bot
Рзаве название bot не будет по умолчанию? И лучше называть бэкэнд, так как будет ещё фронтэнд контейнер

2022-09-10 20:56 UTC, AntonZelinsky commented on requirements.txt
> +pyTelegramBotAPI~=4.7.0
Вообще, договаривались использовать библиотеку python-telegram-bot!(

2022-09-10 20:56 UTC, AntonZelinsky commented on src/server/main.py
> +async def hello():
Эту штуку создавай в каком-нибудь роуте. посмотри как делается тут https://fastapi.tiangolo.com/tutorial/bigger-applications/

2022-09-10 20:56 UTC, AntonZelinsky commented on src/server/main.py
> +app = FastAPI()
Я считаю, что инициализация проекта (и бота и апи) должна быть в каком-то одном месте. +На проекте будет несколько десятков апишек и у каждого из них будут свои роуты или подроуты. 
Поэтмоу, я предлагаю инициализацию вынести в файл main в папку src, а файл run вынести в корень проекта, так как при клонировании или докер контейнере будет открываться корневая папка и нужно будет специально заходить в папку src чтобы запустить, не очень удобно. В файле main так же инициализировать бот, но обработчики и логика должна быть в папке бот.

PS: папка server имеет плохое название, сервер обчень общее и непонятое, лучше назвать api

2022-09-10 20:56 UTC, AntonZelinsky commented on src/core/settings.py
> +env.read_env(str(BASE_DIR / ".env"))
Файл .env не закомичен, код у других не запустится.

2022-09-10 20:56 UTC, AntonZelinsky commented on docker-compose.yaml
> +    container_name: bot
Этот докер-композ файл запускает два образа, как для рабочего приложения, добавь пожоалуйста ещё один такой же файл, только без бэкэнда и добавь приставлку local, чтобы разработчики могли локально запустить этот контейнер и у них крутилась база на которой разрабатывалось приложение. +всякие логины и пароли должны сразу подходить к бэкэнду, то есть храниться в файле .env (у тебя вроде это и так сделано, но решил обратить внимание). 
И хотя бы пару строк добавить в ридми, чтобы новый человек сразу соорозил, что нужно вписать свой токен в конфиг, запустить докер-композ файл и как запустить приложение

2022-09-12 06:18 UTC, cement-hools commented on Dockerfile
> +COPY ./requirements.txt .
хотел вынести в отдельный слой, чтобы не устанавливались зависимости каждый раз

2022-09-12 06:22 UTC, cement-hools commented on requirements.txt
> +pyTelegramBotAPI~=4.7.0
Наташа написала что именно pyTelegramBotAPI @NataliyaPavlova
какой в итоге оставляем?

2022-09-12 06:34 UTC, cement-hools commented on src/core/settings.py
> +env.read_env(str(BASE_DIR / ".env"))
файл не должен быть в репозитории. там секретная информация

2022-09-12 06:41 UTC, cement-hools commented on src/server/main.py
> +app = FastAPI()
что то не получается бота обьявить в main а хендлер прописать в другом модуле

2022-09-12 17:54 UTC, cement-hools commented
Не получается запустить создание миграций!

НЕ ПОЛУЧАЕТСЯ ЗАПУСТИТЬ bot_app.run_polling() ВМЕСТЕ С FASTAPI СЕРВЕРОМ

2022-09-12 19:30 UTC, AntonZelinsky commented on Dockerfile
> +COPY ./requirements.txt .
Точно, слышал об этом уже однажды. Добавь, пожалуйста, комент, почему отдельно копируется файл зависимостей.

2022-09-12 21:48 UTC, AntonZelinsky commented on src/core/settings.py
> +env.read_env(str(BASE_DIR / ".env"))
Нет, файл должен быть в репозитории, либо .env.example, либо .env.local (и подхватываться автоматически если нет .env). Я сейчас склонировал репозиторий и знаешь что? Я не смог его запустить! И мне руками нужно подбирать все параметры к конфиг файлу( Хотел помочь, но ....

2022-09-13 04:59 UTC, cement-hools commented on src/core/settings.py
> +env.read_env(str(BASE_DIR / ".env"))
добавил

2022-09-14 06:50 UTC, NataliyaPavlova commented on src/api/routers.py
> +@router.post("/hello")
по endpoint /hello нужен все-таки GET, чтобы это работало

2022-09-14 06:50 UTC, NataliyaPavlova commented on .env.example
> +BOT_TOKEN=
Макс, а добавь еще и .env файл в репозиторий? чтобы народ мог у себя запустить.

2022-09-14 06:50 UTC, NataliyaPavlova commented on requirements.txt
> +python-telegram-bot==20.0a1
вышла уже версия 20а4, давай придерживаться практики использовать свежие версии.

2022-09-14 06:50 UTC, NataliyaPavlova commented on src/api/routers.py
> +@router.post("/hello")
поправь, пожалуйста на @router.get, для удобства тех, кто будт endpoints дальше делать.

2022-09-14 06:50 UTC, NataliyaPavlova commented on .env.example
> +DB_NAME=  # имя базы данных
Макс, это добротная работа!
Отдельный тебе плюс в карму за то, что пишешь комментарии и докстринги.

Напиши, пожалуйста, еще в README как запускать этот проект со всеми случаями (локально, через докер, только бота, бота и апи) Несколько комментариев по коду ниже.

2022-09-14 06:50 UTC, NataliyaPavlova commented on run.py
> +    await start_bot()
еще надо бы базу инициализировать при старте апи, у тебя вроде была такая строчка

2022-09-14 06:50 UTC, NataliyaPavlova commented on src/bot/handlers.py
> +START_TEXT = (
(править не надо, на будущее) тексты лучше вынести в отдельный файл. Если потом заказчик или продакт захочет поменять тексты, не надо будет по всему проект у искать их

2022-09-14 06:50 UTC, NataliyaPavlova commented on src/core/db/models.py
> +
давай использовать sqlalchemy. Там удобно типы декларировать или прописывать отношения между таблицами.
Вот тут можно почитать, как декларировать модели: https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/

2022-09-14 06:50 UTC, NataliyaPavlova commented on src/core/db/models.py
> +    id: int = Field(primary_key=True, nullable=False)
для айди 
from sqlalchemy.dialects.postgresql import UUID

id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        unique=True,
        nullable=False,
    )

2022-09-14 06:50 UTC, NataliyaPavlova commented on src/core/db/models.py
> +class BaseModel(SQLModel):
лучше назвать класс по-другому: во-первых, название сделать говорящим, а во-вторых BaseModel это вполне конкретный класс из pydantic

мне нравится идея называть такие классы mixin, например, TimestampMixin\IDMixin

2022-09-14 07:37 UTC, cement-hools commented on src/api/routers.py
> +@router.post("/hello")
post тоже же работает

2022-09-14 07:38 UTC, cement-hools commented on .env.example
> +BOT_TOKEN=
такие данные хранить в ропозитории это плахая практика. пусть лучше будет в slack или в notion

2022-09-14 07:40 UTC, cement-hools commented on requirements.txt
> +python-telegram-bot==20.0a1
python-telegram-bot~=20.0a1 будет скачена последняя

2022-09-14 07:45 UTC, cement-hools commented on src/core/db/models.py
> +
ты же написала использовать pydantic, специально искал такую библиотеку

> 1) модель Shift

Использовать либу pydantic  [https://pydantic-docs.helpmanual.io/usage/models/](https://pydantic-docs.helpmanual.io/usage/models/) .

2022-09-14 08:40 UTC, cement-hools commented on src/core/db/models.py
> +class BaseModel(SQLModel):
mixin немного другое

> [Mixin классы](https://docs-python.ru/tutorial/klassy-jazyke-python/takoe-klassy-miksiny/) - это концепция в 
> программировании, в которой класс предоставляет функциональные возможности, но не предназначен для самостоятельного использования. Основная цель миксинов - предоставить какие-то дополнительные методы.

2022-09-14 08:44 UTC, cement-hools commented on src/bot/handlers.py
> +START_TEXT = (
Вообще это в БД надо хранить, чтобы из админки поменять

2022-09-14 13:41 UTC, AntonZelinsky commented on requirements.txt
> +python-telegram-bot==20.0a1
20.0а4 последняя сейчас.

2022-09-14 13:44 UTC, AntonZelinsky commented on .env.example
> +BOT_TOKEN=
Вообще пофигу, там же токен не от продакшена хранится будет. А даже имея токен, ничего с ботом не сделаешь, нужно знать id пользователя которому максимум моно отправить сообщение, если бот запущен, то другому нельзя будет получить и сообщения от пользователя. Но вообще, токен комитать не нужно, так как у каждого он свой, уникальный.

А вот данные для подключения к базу нужно закомитать! Данные должны быть под локальный запуск, так как без них не запустится ни контейнер с базой, ни приложение. Делаем максимально гладкий вход для разработчиков, чтобы в один клик всё запускалось. 
Если создали этот файл, то уже .env делать особого смысла нет, чтобы не дублировать, но этот файл должен быть полностью заполнен, кроме токена бота.

2022-09-14 14:28 UTC, AntonZelinsky commented on src/bot/handlers.py
> +START_TEXT = (
Моё мнение, что если это можно не делать, то лучше не делать вообще.) Когда эти тексты не нужно менять постоянно, когда нет поддержки локализации, то зачем вообще тратить время на разработку и поддержку неиспользуемого функционала? Это худшее что можно сделать в проекте!

Докину вам ещё один вариант, можно сделать просто список констант и использовать их) можно создать константы там где используются, либо в один внешний файл вынести.

И файл и база имеет свои недостатки, но обычно, всегда есть какой-то файл со всеми константами на одном языке, которые потом используются как ключ в базе, s3 или любом другом хранилище.

Но опять же, нам это делать не нужно, тем более из админки менять что-то.
Наташа, нужно будет следить, чтобы студенты не выносили из функций текстовые константы, так как это всё очень любят делать, а ещё, любят написать свою систему перевода или динамической смены языка...( И при том, каждый делает это по своему параллельно друг другу.)
Потом, под конец проекта подумаем нужно ли нам это делать и сделает кто-то один, по нашему тех заданию.

2022-09-14 15:30 UTC, NataliyaPavlova commented on src/api/routers.py
> +@router.post("/hello")
ну я не видела, чтобы hello world был постом) 
а потом, ты это делаешь для следующих разрабов. У нас в апи endpoints все гет, насколько я помню

2022-09-14 15:32 UTC, cement-hools commented on docker-compose.yaml
> +    container_name: bot
База и так будет локальная, запускается же на локальном компьютере

2022-09-14 15:33 UTC, cement-hools commented on src/api/routers.py
> +@router.post("/hello")
НУ вообще пусть учатся). ну если хочешь исправлю

2022-09-14 15:34 UTC, AntonZelinsky commented on src/core/db/models.py
> +
Пидантик для апи, для входных и выходных данных, а для базы свои модели и библиотека. Не вижу сильной разницы между твоим вариантом и [стандартным от sqlalchemy, ](https://docs.sqlalchemy.org/en/14/orm/tutorial.html#declare-a-mapping) разве только то, что будет аннотация типа чуть лучше, но по сути, это так же обвёртка на стандартным, как и у той библиотеки, которую прислала Наташа. 
Предлагаю, всё же использовать стандартную, не добавляя новые зависимости.

P.S.: для updated_at нужен триггер на изменение. И с текущим дефолтом точно будут проблемы, насколько я помню, он выполнтся при запуске и будет одно и то же время везде проставлть, либо что-то то подобное. 
В [этом примере бота с апишкой, ](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/models.py#L83) решали проблему с тригером и стандартным дефолтом, нам нужно что-то такое.

2022-09-14 15:42 UTC, cement-hools commented on src/core/db/models.py
> +
Через эту либу модели из БД можно сразу выдавать в тело ответа для FastAPI.
А так предется переваодить в pydantic/
Ну если хотите сделаю sqlalchemy

2022-09-14 15:44 UTC, NataliyaPavlova commented on src/core/db/models.py
> +
ой, точно.
ты все равно использовал не pydantic, а либу уровнем выше. Давай пока оставим.

2022-09-14 15:44 UTC, NataliyaPavlova commented on README.md
> +```
я просила написать еще, как запускать отдельно бота.

2022-09-14 15:44 UTC, NataliyaPavlova commented on docker-compose.yaml
> +    container_name: bot
сделай все-таки докер, м? как показала практика, удобнее, клгда есть еще локальный докер-компоуз) и не надо конфиг переписывать (когда база локальная, хост - localhost,  когда в докере - название сервиса)

2022-09-14 15:47 UTC, cement-hools commented on README.md
> +```
А для чего? если все запускается нормально

2022-09-14 16:03 UTC, AntonZelinsky commented on src/core/db/models.py
> +
> Через эту либу модели из БД можно сразу выдавать в тело ответа для FastAPI.
> А так предется переваодить в pydantic

Это как раз антипаттерн больших приложений, ты будешь возвращать фронту не то что ему нужно, а то что есть в базе. Причём, если будет какой-то join, то в 100 раз больше чем нужно, в том числе и приватных данных. А если нужно вернуть или добавить в базу два поля из одной таблицы, а два поля из другой, как ты решишь эту проблему? Даже id, дата создания и изменения, это очень важные штуки, но как правило, в 90% случаев они не должны торчать наружу. А, как правило, на вход апи будет приходить 1-2 параметра из базы и ты будешь отдавать 1-2 в ответ, а не целую строку таблицы. Это очень сильно нарушает принцип закрытости.

Вообще, в n-уровненвых архитектурах, на каждый уровень может быть свой маппер(конвернет) данных, но даже когда это очень упрощённая архитектура, всё равно, всегда отделяют модели апи от моделей базы данных.

2022-09-14 16:17 UTC, cement-hools commented on src/core/db/models.py
> +
Ну давайте будем мапить из Pydantic а не sqlalchemy

2022-09-14 16:18 UTC, AntonZelinsky commented on src/bot/handlers.py
> +async def test(context: CallbackContext) -> None:
Эта функция нигде не подключается к приложению, значит её нужно удалить

2022-09-14 16:21 UTC, cement-hools commented on docker-compose.yaml
> +    container_name: bot
база в контейнере

2022-09-14 16:28 UTC, cement-hools commented on docker-compose.yaml
> +    container_name: bot
@AntonZelinsky, @NataliyaPavlova 

Подскажите что не так.
работаешь локально, локальная база, развернул compose на сервере - база будет на сервере

2022-09-14 18:05 UTC, AntonZelinsky commented on docker-compose.yaml
> +    container_name: bot
С базой кажется что всё норм, пусть файл остаётся, он пригодится для деплоя на сервер, хотя скорее сего, будет ещё дорабатываться, чтобы не тянуть все исходники, а только один докер-композ файл на сервер.
Просил добавить ещё docker-compose.local.yaml, в котором будет запускаться только база данных. Это очень удобно для локальной разработки, разработчику не нужно устанавливать базу, ковыряться в конфигах, а просто запустил файл и всё работает. Кто не захочет, будет использовать локальную базу, но нам главное дать удобный инструмент.

2022-09-14 18:07 UTC, cement-hools commented on docker-compose.yaml
> +    container_name: bot
есть пример?

2022-09-14 21:20 UTC, AntonZelinsky commented on src/core/db/models.py
> +
А зачем? ты сначала получаешь модель sqlalchemy, мапишь её в что-то среднее между  Pydantic и sqlalchemy, а потом ещё раз в  Pydantic. Тянется куча новых зависимостей, появляется новый код, время работы замедляется, а плюсов у этого решения только чуть-чуть улучшенная аннотация. 
Я могу быть не прав, буду тогда рад, если поделишься и расширишь мою картину)

2022-09-15 07:16 UTC, NataliyaPavlova commented on src/core/db/models.py
> +    status = Column(String, nullable=False)
У нас поле статус принимает короткий набор конкретных значений, и мне кажется логичным все-таки через Enum сделать. Чтобы не было потом для старта смены, например, статусов "started"/"activated"/"launched" и тд.
https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ENUM

у твоего ПР дофига комментов, и наверняка тебя уже достало все исправлять. Но это вобще первый реквест в проекте, поэтому 1) должно быть максимально удачно для дальнейшей разработки все реализовано и 2) мы все пока адаптируемся, учимся и "срабатываемся" друг с другом. Тем, кто дальше будет делать задачи, будет проще (вдруг эта светлая мысль тебя успокоит:))

2022-09-15 11:26 UTC, NataliyaPavlova approved these changes

2022-09-15 14:20 UTC, AntonZelinsky approved these changes

2022-09-15 14:20 UTC, AntonZelinsky commented on requirements.txt
> +sqlmodel~=0.0.8
Удали лишнюю зависимость

2022-09-15 14:28 UTC, merged