add User and Request models
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #10
Opened 2022-09-17 17:49 UTC by niktere12321

2022-09-17 19:08 UTC, petrovskydv requested changes

2022-09-17 19:08 UTC, petrovskydv commented on src/core/db/models.py
> +            raise ValueError('Адресс слишком короткий')
опечатка в слове Адрес

2022-09-17 19:08 UTC, petrovskydv commented on src/core/db/models.py
> +    approved = Column(approved_choices, nullable=False)
поле должно называться status, ориентируйся по [схеме БД ](https://www.notion.so/477c62f7eb4640efab2d9364ff4de8f5) в notion 
при создании заявки статус должен быть равен pending

2022-09-17 19:08 UTC, petrovskydv commented on src/core/db/models.py
> +        return f'<Request: {self.id}, approved: {self.approved}>'
approved надо заменить на status

2022-09-17 19:08 UTC, petrovskydv commented on src/core/db/models.py
> +    """Модель для пользователей"""
нужно добавить поле для telegram_id, чтобы мы могли посылать пользователю сообщения.

2022-09-17 19:18 UTC, NikolaySolop commented on src/core/db/models.py
> +    address = Column(String(50), nullable=False)
по [схеме БД](https://www.notion.so/477c62f7eb4640efab2d9364ff4de8f5) поле называется city

2022-09-17 20:06 UTC, NikolaySolop commented on src/core/db/models.py
> +        if len(str(value)) == 11:
тут наоборот, если не равен 11, то ошибка

2022-09-17 20:12 UTC, NikolaySolop commented on src/core/db/models.py
> +        return value.upper()
метод title()

2022-09-17 20:13 UTC, NikolaySolop commented on src/core/db/models.py
> +    phone_number = Column(INTEGER, unique=True, nullable=False)
количество разрядов телефона выходит за пределы INTEGER, при попытке записи будет ругаться. Нужен BIGINT

2022-09-18 00:13 UTC, AntonZelinsky approved these changes, later dismissed

2022-09-18 00:13 UTC, AntonZelinsky commented on src/core/db/models.py
> +            raise ValueError('Адрес не корректны')
Так город или адрес?

2022-09-18 00:13 UTC, AntonZelinsky commented on src/core/db/models.py
> +    approved_choices = ENUM(
approved_choices — что это вообще за имя? одобренный выбор? и как это понимать? 
Кажется, правильнее называть request_statuses, из этого названия сразу понятно что это за переменная и что будет внути. 
(и попарвь сразу имя у status_choices, там тоже можно назвать получше)
+ давай ещё добавим один статус — repeat pending, когда человеку отказали в участии, но он подался ещё раз.

2022-09-18 01:00 UTC, AntonZelinsky commented on src/core/db/models.py
> +    approved_choices = ENUM(
В вообще, что-то я затупил, нам не подходит такой способ описания енамок, ведь его нельзя использовать нигде в коде. Нужно сделать как [класичекий енам от питона](https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.Enum). Тогда к нему можно обращаться как к объекту в коде, сравнивать статусы и всё остальное.
Но вооще, оказывается [есть проблема у библиотеки ](https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.Enum)генерации алембика с енамами и постгрес.( Хотя вроде как к этому [есть и решение](https://medium.com/uncountable-engineering/coherent-python-and-postgresql-enums-using-sqlalchemy-3bb23d9d369a), [другой пример](https://makimo.pl/blog/upgrading-postgresqls-enum-type-with-sqlalchemy-using-alembic-migration/).

2022-09-18 09:29 UTC, petrovskydv requested changes

2022-09-18 09:29 UTC, petrovskydv commented on src/core/db/models.py
> +class Request_statuses(str, enum.Enum):
нужно использовать CamelCase в названиях классов. Request_statuses -> RequestStatus. И в единственном числе.

2022-09-18 09:29 UTC, petrovskydv commented on src/core/db/models.py
> +class Shift_statuses(str, enum.Enum):
нужно использовать CamelCase в названиях классов. И в единственном числе.

2022-09-18 10:44 UTC, NataliyaPavlova commented on src/core/db/models.py
> +    telegram_id = Column(INTEGER, unique=True, nullable=False)
ой, номер телефона я бы все-таки строкой сделала, чтобы уж точно не возникало экспоненциальной нотации. Номер телефона как 8.91E+10 это бррр

2022-09-18 10:44 UTC, NataliyaPavlova commented on src/core/db/models.py
> +        if re.compile(regex).search(value) is None:
а если из одних пробелов или дефисов? давай добавим проверку на  наличие букв?

2022-09-18 10:47 UTC, NataliyaPavlova commented on src/core/db/models.py
> +    telegram_id = Column(INTEGER, unique=True, nullable=False)
а ты уверен, что telegram_id влезет в integer?
https://core.telegram.org/bots/api#chat

2022-09-18 18:58 UTC, AntonZelinsky approved these changes, later dismissed

2022-09-18 18:58 UTC, AntonZelinsky commented on src/core/db/models.py
> +            if re.search(regex_words, value) is None:
эти два ифа можно объеденить в один и проверять на None не обязательно, только перепроверь, а не просто переиспользуй прдложенный мной вариант
```suggestion
        if re.search(regex, value) is None &&  re.search(regex_words, value):
```

2022-09-18 18:58 UTC, AntonZelinsky commented on src/core/db/models.py
> +    user_id = Column(
Пишу скорее тимлидам, что в ПРах с апи, обязательно нужно описывать [отношения в объектом виде](https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html), чтобы можно было удобно пользоваться моделями и их связями. Тут не требую, так как сложно протестировать, нужно получать данные с базы, а здесь сложно протетстить. Добавления объектных отношений, по идее, не должно менять ничего в базе.

2022-09-18 18:58 UTC, AntonZelinsky commented on src/core/db/models.py
> +from sqlalchemy.dialects.postgresql import ENUM, UUID
Добавь ENUM алиас pg_enum, чтобы одинаковые названия не путались

2022-09-19 08:10 UTC, petrovskydv requested changes

2022-09-19 08:10 UTC, petrovskydv commented on src/core/db/models.py
> +import phonenumbers
нужно внести в зависимости проекта

2022-09-19 09:09 UTC, petrovskydv submitted a review, later dismissed

2022-09-19 14:18 UTC, NataliyaPavlova submitted a review, later dismissed

2022-09-19 16:51 UTC, petrovskydv approved these changes, later dismissed

2022-09-20 06:07 UTC, ADesBiysk approved these changes

2022-09-20 06:12 UTC, merged