Refactoring: data_factory ( https://www.notion.so/Refactoring-data_factory-76cec4ddbbeb4b649ab60a4167f57213)
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #103
Opened 2022-11-20 14:23 UTC by elityaev

Настроено заполнение БД тестовыми данными согласно условиям задачи. 
py -m data_factory.main --delete - команда для заполнения БД с удалением существующих данных из таблиц.

2022-11-20 19:48 UTC, Wiped-Out requested changes

2022-11-20 19:48 UTC, Wiped-Out commented on data_factory/factories.py
> +        if self.status == "started":
Лучше не харкодить статусы в ифах. Можно переделать под сравнение с Enum (models.Shift.Status)

2022-11-20 19:48 UTC, Wiped-Out commented on data_factory/main.py
>      print("Удаление данных из таблиц...")
Не критично, но лучше принты заменить на логирование

2022-11-20 19:48 UTC, Wiped-Out commented on data_factory/main.py
> +        started_shift = ShiftFactory.create(status='started')
Захардкоженный статус. Лучше изменить на Enum

2022-11-20 19:48 UTC, Wiped-Out commented on data_factory/main.py
> +        preparing_shift = ShiftFactory.create(status="preparing")
Захардкоженный статус. Лучше изменить на Enum

2022-11-20 19:48 UTC, Wiped-Out commented on data_factory/main.py
> +        finished_shifts = ShiftFactory.create_batch(FAKE_FINISHED_SHIFTS_COUNT, status='finished')
Захардкоженный статус. Лучше изменить на Enum

2022-11-20 19:48 UTC, Wiped-Out commented on data_factory/main.py
> +def generate_fake_data() -> None:
Довольно большая и трудночитаемая функция. Предлагаю ее разделить. Можно вынести в отдельные функции генерацию по статусу (например, generate_started_shifts(), generate_preparing_shifts() и generate_finished_shifts() ), а потом их вызывать в основной функции generate_fake_data()

2022-11-20 20:44 UTC, ADesBiysk reviewed
1. Нужна еще инструкция по запуску. Я бы создал в этой директории файл readme.md.
2. Нужно добавить библиотеку click в poetry.
3. print точно надо убрать, логирование можно настроить не только в файл, но и консоль.
Если примитивно, то так
def get_logger(log_filename: str) -> logging.Logger:
    file_handler = logging.FileHandler(filename=log_filename)
    stdout_handler = logging.StreamHandler(stream=sys.stdout)
    handlers = [file_handler, stdout_handler]

    logging.basicConfig(
        encoding='utf-8',
        level=logging.INFO,
        handlers=handlers,
    )
    return logging.getLogger(__name__)

2022-11-20 20:44 UTC, ADesBiysk commented on data_factory/factories.py
> +        "date_between_dates", date_start=datetime.date(2012, 1, 1), date_end=datetime.date(2016, 1, 1)
Вынеси эти даты в виде констант в начало файла.

2022-11-20 20:44 UTC, ADesBiysk commented on data_factory/factories.py
> +    final_message = factory.Faker("text", max_nb_chars=25)
Лучше final_message сделать текст длиннее. И еще есть опции переменной длины генерируемого текста.

2022-11-20 20:44 UTC, ADesBiysk commented on data_factory/main.py
> +    flag()
Название не информативное.

2022-11-21 14:25 UTC, elityaev commented
Замечания исправлены + изменил в корневой README.md информацию о тестовых данных

2022-11-21 18:18 UTC, Wiped-Out approved these changes

2022-11-21 18:18 UTC, Wiped-Out commented on data_factory/main.py
> +def get_logger(log_filename: str) -> logging.Logger:
Не критично, но лучше настройку логгера вынести из main.py в core/config.py

2022-11-21 18:26 UTC, AntonZelinsky commented on data_factory/factories.py
> +MIN_USER_BIRTH_DATE = datetime.date(2016, 1, 1)
Сделайте период в 30 лет, чтобы данные были более похожи на реальные

2022-11-21 20:27 UTC, AntonZelinsky reviewed
В функциях генерации смен чёрт голову сломает!
Нужно переписать их! Механизм генерации у фактори бой позволяет писать довольно очень красивый, простой декларативный код и хорошо бы придерживаться этого подхода (в данном случае, императивный подход — зло!). 


Тебе нужно пересмотреть весь алгоритм. 
Что такое смена? Это десяток пользователей и заявки от них.
Если смена запущена, то ещё и задачи для выполнения. Если смена финишировала, то все задачи должны иметь статус.

Итого, сперва, тебе нужно создать пользователей и смену в прошлом. 
- Из списка пользователей взять рандомные ±`n` пользователей  и создать для их requests, половину заапрувить, а половину задеклайнить (это всё делается декларативным методом, то есть без циклов, по сути, в параметры фабрики передаются какие-то параметры которые указывают какие значения должны быть установлены, в твоём случае, нужно два раза вызвать генерацию реквестов и тот запрос который генерирует со статусом апрув сохранять в переменную, для дальнейшей работы)
- Для заапрувленных пользователей создать UserTasks на количество дней и тут тоже выбрать рандом для различных статусов (статус `исключён` можно не использовать, чтобы не ломать бизнес модель)
- Для пользовательских задач вызвать фабрику создания фотографий (хотя можно это не делать, так как в другой задаче выпиливается)

По сути, всё описывается командами и без циклов. По изучай библиотеку, которую используешь и какие-нибудь различные сложные примеры. Посмотри этот [репозиторий ](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/factories.py), там очень крутые фабрики написали.

2022-11-21 20:27 UTC, AntonZelinsky commented on data_factory/main.py
>      if input(msg).lower().strip() not in ("y", "yes"):
Раз уже успользуешь клик, то и ввод принимай из него.

2022-11-21 20:27 UTC, AntonZelinsky commented on data_factory/main.py
> +        TaskFactory.create_batch(FAKE_TASK_COUNT)
Ой, а давай не будем выносить в отдельные переменные эти значения, по крайней мере за пределами этой функции. А то очень тяжело смотреть код, приходится больше чем на 100 строк скролить вверх, чтобы посмотреть значение. 
Заданий сделай 40.

2022-11-21 20:27 UTC, AntonZelinsky commented on data_factory/main.py
> +        task_ids_list = task_ids_list.scalars().all()
Фабрики возвращают [записи которые](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/core/management/commands/filldb.py#L140) они создают для будущего переиспользования

2022-11-22 01:47 UTC, ADesBiysk commented
> В функциях генерации смен чёрт голову сломает! Нужно переписать их! Механизм генерации у фактори бой позволяет писать довольно очень красивый, простой декларативный код и хорошо бы придерживаться этого подхода (в данном случае, императивный подход — зло!).
> 
> Тебе нужно пересмотреть весь алгоритм. Что такое смена? Это десяток пользователей и заявки от них. Если смена запущена, то ещё и задачи для выполнения. Если смена финишировала, то все задачи должны иметь статус.
> 
> Итого, сперва, тебе нужно создать пользователей и смену в прошлом.
> 
> * Из списка пользователей взять рандомные ±`n` пользователей  и создать для их requests, половину заапрувить, а половину задеклайнить (это всё делается декларативным методом, то есть без циклов, по сути, в параметры фабрики передаются какие-то параметры которые указывают какие значения должны быть установлены, в твоём случае, нужно два раза вызвать генерацию реквестов и тот запрос который генерирует со статусом апрув сохранять в переменную, для дальнейшей работы)
> * Для заапрувленных пользователей создать UserTasks на количество дней и тут тоже выбрать рандом для различных статусов (статус `исключён` можно не использовать, чтобы не ломать бизнес модель)
> * Для пользовательских задач вызвать фабрику создания фотографий (хотя можно это не делать, так как в другой задаче выпиливается)
> 
> По сути, всё описывается командами и без циклов. По изучай библиотеку, которую используешь и какие-нибудь различные сложные примеры. Посмотри этот [репозиторий ](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/apps/info/factories.py), там очень крутые фабрики написали.

2022-11-23 09:33 UTC, elityaev commented
Допустим создаю пользователей и завешенную смену, потом делаю рандомную выборку 30 юзеров и к каждому из них реквесты в эту смену например 15 одобренных и 15  отклоненных, при этом, указывая в параметрах id конкретной смены. Т.е. нужно пробежаться по всем юзерам. Как сделать это без цикла я не пойму. По заданию, нужно 18 завершенных смен и по всем нужно пробежаться для назначения реквестов. Тут тоже не вижу других вариантов кроме цикла. 
Есть вариант создавать последовательно вложенные сущности, т.е. например при создании завершенной смены создавать определенное количество запросов с разными статусами, а в RequestFactory для каждого запроса создавать юзера(правда не будет выполняться условие задачи, чтобы несколько участников участвовали в разных сменах).  Ну а дальше можно было бы по цепочке к одобренным заявкам создавать задания и тут нужно создавать хитрый метод для назначения даты задания, последовательно, без повторений дат (если для завершенной смены, при условие не использования статуса исключенный, подойдут только статусы одобрено, то для активной смены нужны статусы одобрено по задачам до текущей даты, в текущую дату статус на рассмотрении, после текущей даты - статус новые).  Тут у меня тоже загвоздка.

2022-11-24 19:03 UTC, ADesBiysk commented
> Допустим создаю пользователей и завешенную смену, потом делаю рандомную выборку 30 юзеров и к каждому из них реквесты в эту смену например 15 одобренных и 15 отклоненных, при этом, указывая в параметрах id конкретной смены. Т.е. нужно пробежаться по всем юзерам. Как сделать это без цикла я не пойму. По заданию, нужно 18 завершенных смен и по всем нужно пробежаться для назначения реквестов. Тут тоже не вижу других вариантов кроме цикла. Есть вариант создавать последовательно вложенные сущности, т.е. например при создании завершенной смены создавать определенное количество запросов с разными статусами, а в RequestFactory для каждого запроса создавать юзера(правда не будет выполняться условие задачи, чтобы несколько участников участвовали в разных сменах). Ну а дальше можно было бы по цепочке к одобренным заявкам создавать задания и тут нужно создавать хитрый метод для назначения даты задания, последовательно, без повторений дат (если для завершенной смены, при условие не использования статуса исключенный, подойдут только статусы одобрено, то для активной смены нужны статусы одобрено по задачам до текущей даты, в текущую дату статус на рассмотрении, после текущей даты - статус новые). Тут у меня тоже загвоздка.

Если посмотреть пример из репозитория любимовки, то можно увидеть несколько интересных способов
1. методы batch_create возвращают созданные объекты, а значит их можно не брать из БД, а брать нужное количество из списка.
users = UserFactory.create_batch(FAKE_USERS_COUNT)
Далее, где нужны пользователи: shift_users = random.choices(users, 5) и передавать их в фабрику.

2. Все связанные данные прописываются в фабрике, например:
@restrict_factory(general=(Person,))
class FestivalTeamFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = FestivalTeamMember
        django_get_or_create = ("person", "team")

    team = factory.Iterator(FestivalTeamMember.TeamType.values)
    position = factory.Faker("job", locale="ru_RU")
    is_pr_director = False

    @factory.lazy_attribute
    def person(self):
        queryset = Person.objects.filter(city__isnull=False, email__isnull=False).exclude(image__exact="")
        person = get_random_objects_by_queryset(queryset)
        return person

get_random_objects_by_queryset прописана отдельно и она просто берёт указанное количество случайных записей из нужной модели.

В некоторых местах, пока тоже не вижу как сделать без цикла. 
Надо убрать запросы в БД напрямую и переиспользовать генерируемые данные в виде списков. Код станет проще, и тогда, легче будет увидеть, как избавиться от циклов.

2022-11-27 02:59 UTC, AntonZelinsky commented
Может полностью избавиться не получится, но нужно очень постараться. 
Посмотри ещё раз фабрики в репозиторие Любимовки. Как п[ример, эта фабрика создаёт е](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/79c5948a6d53f9748dddf795c672cadba14da490/apps/articles/factories/blog_items.py#L137)щё десяток других записей в других таблицах с очень сложной структурой и ни одного цикла!

2022-12-02 00:07 UTC, AntonZelinsky approved these changes
Если всё работает, то думаю, что можно мержить. Как только будут выкачены последние обновления с members, нужно будет немного доработать эти фабрики и подумать, кк улучшить то что есть сейчас

2022-12-02 00:07 UTC, AntonZelinsky commented on data_factory/factories.py
> +            started_at = last_started_shift.started_at - timedelta(days=random.randrange(4, 7)) - timedelta(days=90)
В целом, прикольно получилось. Но добавь, пожалуйста, комментарии. Я с раза третьего только въехал во всю глубину этого кода.)
В ифах выше и ниже тоже добавь коменты, что они делают, в одно предложение опиши, этого достаточно.

константу STARTED_SHIFT_DURATION можно убрать и использовать числа, так ты делал это в других местах этого класса. 

и SESSION сделай меленького регистра, а то вводит в заблуждение, выглядит так, как будто какая-то константа. МОжешь нижнее подчёркивание добавить, если хочется.)

2022-12-02 00:07 UTC, AntonZelinsky commented on data_factory/factories.py
> +        if self.task_date == datetime.date.today():
По идее, это должны быть рандомные статусы из списка

2022-12-02 00:07 UTC, AntonZelinsky commented on data_factory/main.py
> +        finished_shifts = ShiftFactory.create_batch(1, status=Shift.Status.FINISHED)
Вынеси создание смен в отдельные функции, чтобы код был легче к восприятию.

2022-12-02 14:51 UTC, ADesBiysk approved these changes

2022-12-02 18:21 UTC, merged