Fix/registration
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #107
Opened 2022-11-22 14:51 UTC by mspiridonov2706

Задача: https://www.notion.so/Bot-a96778a3d4354e6c84e0561bdbbec551

Добавил ngrok в docker compose. 
Теперь при запуске приложение проверяет, если BOT_WEBHOOK_MODE=False, тогда url для шаблона генерируется с помощью сервиса get_registration_ngrok_url. Сервис обращается к сервису ngrok и парсит из ответа доменное имя, которое сервис выдал при запуске. 
Если BOT_WEBHOOK_MODE=True, тогда url для шаблона генерируется через APPLICATION_URL.

Всё это сделано для обхода ошибки, из-за которой telegram бот не давал обратиться к WebApp.
Подробнее о проблеме написано [здесь](https://www.notion.so/WebApp-Telegram-API-eee8bf6ebcbe492e835bf166ead50fd7) в разделе **Подготовка к тестированию кода на локале**

Так же вместо app.mount создал новый роутер _**/registration_template**_, так как в документации написано что app.mount не поддерживается больше и это работало нестабильно, на 10 кликов по шаблону регистрации в боте в половине случаев шаблон не открывался.

2022-11-22 14:52 UTC, mspiridonov2706 commented on .github/workflows/deploy_stage.yaml
> +            echo NGROK_AUTH_TOKEN=2HUe0ZFrPQS1jsGl023ju7PmARn_3noqbN46jjeqV42EibHCg >> .env
Временный токен, взял свой личный. Нужно создать новый секрет и ввести там другой токен какой-нибудь.

2022-11-22 14:53 UTC, mspiridonov2706 commented on requirements.txt
> +yarl==1.8.1
Сделал это изменение, потому что контейнер стал странно себя вести на сервере
вот [ссылка](https://practicum-students.slack.com/archives/C03SXFKDWJC/p1669125082471129) на ошибки

2022-11-22 15:06 UTC, mspiridonov2706 commented on requirements.txt
> +factory-boy==3.2.1
Сделал это изменение с помощью poetry export -f requirements.txt --output requirements.txt --without-hashes, потому что контейнер стал странно себя вести на сервере
вот [ссылка](https://practicum-students.slack.com/archives/C03SXFKDWJC/p1669125082471129) на ошибки

2022-11-25 11:36 UTC, AntonZelinsky requested changes
Мы делали [исследование](https://www.notion.so/WebApp-Telegram-API-eee8bf6ebcbe492e835bf166ead50fd7), что можно запускать веб приложение и показывать форму без дополнительного сервера. Так и нужно делать! 
Причём, раньше же работало без этого, так зачем усложнять настолько? 

Давай переделаем назад как всё было

2022-11-25 21:04 UTC, mspiridonov2706 commented
> Мы делали [исследование](https://www.notion.so/WebApp-Telegram-API-eee8bf6ebcbe492e835bf166ead50fd7), что можно запускать веб приложение и показывать форму без дополнительного сервера. Так и нужно делать! Причём, раньше же работало без этого, так зачем усложнять настолько?
> 
> Давай переделаем назад как всё было

Добрый день. Я так и сделал как написано в исследовании, только для удалённого сервера. То что в исследовании описано, это работает только для локального тестирования (см пункт Подготовка к тестированию кода на локале) во время которого нужно запускать ngrok. Для того чтобы это убрать нужна https ссылка (которую даёт ngrok), чтобы это заработало без усложнений нужно доменное имя с выданным на него сертификатом. Либо сертификат на IP адрес тестового сервера.

2022-11-27 01:16 UTC, AntonZelinsky commented
Окей, я понял всю суть фитчи и что ты сделал и зачем. Извини за наезд.)
Но всё равно, решение с ngrok нам не подходит. Нужно давать ссылку на наш сервер, чтобы nginx отдавал html страницу. То есть, тебе нужно будет сконфигурировать путь в nginx. 

Как хак, можно указывать на сырой исходник в гитхабе, пример, https://raw.githubusercontent.com/Studio-Yandex-Practicum/lomaya_baryery_backend/develop/src/html/registration.html 

В исходниках была такая штука, но видно что-то было не такс сконфигурировано и не хотело работать 
![image](https://user-images.githubusercontent.com/1431279/204114936-e7547dff-8dbd-4893-b7e8-096713cddd97.png)

2022-11-28 18:32 UTC, mspiridonov2706 commented
> https://raw.githubusercontent.com/Studio-Yandex-Practicum/lomaya_baryery_backend/develop/src/html/registration.html

Привет, спасибо за замечание. Поправлю.

2022-11-28 18:33 UTC, mspiridonov2706 commented
> Окей, я понял всю суть фитчи и что ты сделал и зачем. Извини за наезд.) Но всё равно, решение с ngrok нам не подходит. Нужно давать ссылку на наш сервер, чтобы nginx отдавал html страницу. То есть, тебе нужно будет сконфигурировать путь в nginx.
> 
> Как хак, можно указывать на сырой исходник в гитхабе, пример, https://raw.githubusercontent.com/Studio-Yandex-Practicum/lomaya_baryery_backend/develop/src/html/registration.html
> 
> В исходниках была такая штука, но видно что-то было не такс сконфигурировано и не хотело работать ![image](https://user-images.githubusercontent.com/1431279/204114936-e7547dff-8dbd-4893-b7e8-096713cddd97.png)

Привет, спасибо за замечание. Поправлю.

2022-11-29 01:30 UTC, AntonZelinsky commented
Подмержи к себе девелоп ветку, чтобы конфликты не росли.

Давай так, сделай отдельный ПР, котоырй заставит nginx корректно сервер отдавать эту html страницу. Только перемести её в папку статик. Потом, будем думать как интегрировать. А то пока нет корректной формы, то непонятно где искать проблему, может, они именно в этом.

2022-12-01 15:23 UTC, closed without merging