Settings refactor
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #13
Opened 2022-09-18 17:58 UTC by aafedotov

Added pydantic BaseSettings class in settings.py

2022-09-18 21:13 UTC, ADesBiysk commented on .env.example
>  DB_PORT=5432 # порт для подключения к БД
1. Не нужно дублировать данные для подключения к PostgreSQL. Для подключения к БД в файле src/core/db используется только DATABASE_URL. Её и предлагаю оставить, а остальные параметры убрать. 
2. В конце файла нет пустой строки.

2022-09-18 21:13 UTC, ADesBiysk commented on src/core/settings.py
> +    DB_NAME: str
Загружать переменные окружения для БД, кроме DATABASE_URL, тоже нет смысла. Они не будут использоваться.

2022-09-18 21:13 UTC, ADesBiysk commented on src/core/settings.py
> +    DATABASE_URL: str
В pydantic есть тип PostgresDsn. https://pydantic-docs.helpmanual.io/usage/settings/

2022-09-18 21:13 UTC, ADesBiysk commented on src/main.py
>      bot_app.add_handler(CommandHandler("start", start))
Здесь исправили, а про подключение к БД забыли.

2022-09-19 06:13 UTC, aafedotov commented on .env.example
>  DB_PORT=5432 # порт для подключения к БД
Сделано.

2022-09-19 06:13 UTC, aafedotov commented on src/core/settings.py
> +    DB_NAME: str
Сделано.

2022-09-19 06:13 UTC, aafedotov commented on src/core/settings.py
> +    DATABASE_URL: str
Сделано

2022-09-19 06:13 UTC, aafedotov commented on src/main.py
>      bot_app.add_handler(CommandHandler("start", start))
Сделано.

2022-09-19 06:19 UTC, aafedotov commented
Внес исправления по замечаниям.

2022-09-19 07:34 UTC, ADesBiysk commented on README.md
> +Перед запуском проекта необходимо создать копию файла
Нужно из документации всё лишнее убрать. Этих переменных уже нет.

2022-09-19 08:33 UTC, petrovskydv commented
.env нужно добавить в .gitignore и только потом удалить, иначе он удалиться у всех.

2022-09-19 08:38 UTC, petrovskydv requested changes

2022-09-19 08:38 UTC, petrovskydv commented on src/core/settings.py
> +    BOT_TOKEN: Optional[str] = None
токен обязательный аргумент, а не опциональный.

2022-09-19 08:49 UTC, NataliyaPavlova commented on README.md
> +Перед запуском проекта необходимо создать копию файла
внеси файл .env.example в .gitignore? чтобы каждый у себя уже ставил свой токен спокойно

2022-09-19 08:49 UTC, NataliyaPavlova commented on .env.example
> +BOT_TOKEN=
что-то тут переменных не хватает. 
Ты уверен, что у тебя бд запускается, и run.py тоже?

2022-09-19 09:04 UTC, ADesBiysk commented on .env.example
> +BOT_TOKEN=
Я поторопился удалить переменные из env. Они для docker нужны. Надо вернуть в readme.md и env.

2022-09-19 16:37 UTC, aafedotov commented
Внес исправления по замечаниям второго ревью.

2022-09-19 16:45 UTC, petrovskydv submitted a review, later dismissed

2022-09-19 19:20 UTC, NataliyaPavlova submitted a review, later dismissed

2022-09-19 19:30 UTC, ADesBiysk approved these changes

2022-09-19 19:30 UTC, merged