Added validators
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #134
Opened 2022-12-09 11:33 UTC by Alexey-Bormotov

Задача 1: https://www.notion.so/BUGSPLUS-31053-body-final_message--d3e83fa7e9a644da9a1cf29637ae8ed2
Добавил валидатор на проверку, что финальное сообщение состоит из цифр.

Задача 2 и 3: https://www.notion.so/BUGSPLUS-31049-body-finished_at--52a8aedc9c6c41d1902909b73da51746 https://www.notion.so/BUGSPLUS-31045-body-started_at--4f38bdc9d9c545d3a6697409905bc67c
Я так понял проблема в том, что по-хорошему нельзя менять дату начала и дату окончания смены отдельно дург от друга, а они меняются. Добавил корневой валидатор для проверки, что оба поля есть в запросе (либо оба отсутствуют). Он перегружает валидатор из модели (родительской) создания смены и вызывает его в случае, если оба поля были в запросе и нужно проверить их правильность (как раз про это следующие три задачи).

Задачи 4, 5 и 6: https://www.notion.so/BUGSPLUS-31037-body--4774a838bf1d4d3fb1d273c9379f8a5f
https://www.notion.so/BUGSPLUS-31033-body--4acfe77bb0114cda956ae9df8551051d
https://www.notion.so/BUGSPLUS-31006-started_at-finished_at-body--4cefd32d4b5b407d86f2ffea259b7b81
Добавил корневой валидатор для проверки, что дата начала не больше и не равна дате окончания смены. Поместил его в модель для создания смены, чтобы можно было применять и для создания и для изменения смены.

Задача 7: https://www.notion.so/BUGSPLUS-31042-final_message-API-228c38f95fbf4f9e91a83960e1aabcbb
По этой задаче ничего не стал делать, т.к. не понимаю....Почему при создании смены не нужно выводить final_massage? Это ж не баг, это фича! Если убирать это поле, то придется отдельную response модель исключительно для создания смены писать. Зачем?

2022-12-09 13:19 UTC, AntonZelinsky reviewed
Задачу 7 делать не нужно, отписал в комменте и таблице.

2022-12-09 13:19 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +            raise ValueError("Финальное сообщение не может состоять только из цифр")
Странная валидация. Наверно QA баг заводили, на который приходится такую проверку делать.( Завтра они заведут баг, что финальное сообщение не может быть только из спец символов. 
Лучше бы тут сделали проверку отсутствия пустого значения и минимальной длинный хотя бы в 10 символов.
Предложенные выше две валидации добавь пожалуйста

2022-12-09 13:19 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
Это вообще какая-то ерунда. Если я создал смену с невалидной датой финиша, мне теперь что, дату старта тоже менять? 
Я тоже не очень понял из описания задач что они на самом деле хотят, но думаю, что все поля передающиеся при сохранении смены должны быть обязательными. Почему они необязательные?
Вся проблема в том, что сохранение смены написано костылём, который я уже множество раз просил убрать. Нельзя так сохранять. Во-первых, в методе обновления нет никакой валидации. Нельзя менять дату старта у смены, которая уже была запущена! Во-вторых, нельзя ничего менять у смены, которая была закончена. В-третьих, смены такой вообще может не быть, а мы пытаемся записать значения.

![image](https://user-images.githubusercontent.com/1431279/206710582-050f7ec7-93be-48f4-88be-7d7140f43a1d.png)

Посмотри как сделан метод создания и переделай похожим образом.

2022-12-10 14:42 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +            raise ValueError("Финальное сообщение не может состоять только из цифр")
Вместо полноценного валидатора добавил в поле параметр min_length=10, так норм?

2022-12-10 14:53 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
Дополнил метод всевозможными проверками. Получилось конечно очень монструозно (мне не нравится, как выглдит), но работает.
1. Если смена отмененная или законченая то её изменить вообще нельзя.
2. Если смена в данный момент запущена (текущая) то у неё нельзя поменять дату начала. Но всё ещё можно поменять дату окончания (правда тогда не понятно, что будет с заданиями для участников смены? Если допустим увеличить длительность смены на пару дней, то как будут раздаваться задания на эти дополнительные пару дней?) Может проще сделать и текущую смену неизменяемой, по крайней мере чтобы нельзя было изменить её даты начала и окончания?
3. Если в запросе на изменение смены передны оба поля started_at и finished_at...то их проверит валидатор (чтобы не лезть в базу данных) и тут всё просто. Но если только одно из двух, то проверка на уровне метода будет...и вот тут конечно дичь. Нужно проверить какое из двух полей передано (а второе вытаскивать из бд) и потом проверить что дата начала не больше и не равна дате окончания.

2022-12-10 14:58 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
А ещё в методе на обновление смены мне не нравится вызов метода для получения смены:
shift = await self.__shift_repository.get(id)
Он конечно выкидывает исключение LookupError, если передать несуществующий id смены в запросе, но сервак при этом всёравно падает; выброшенное исключение видно только в терминале. Как то не айс.

2022-12-10 20:48 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        shift = await self.__shift_repository.get(id)
Замени в AbstractRepository исключение LookupError на NotFoundException, которое уже будет адекватно обработано. Это осталось с того времени, когда кастомных исключений не было.

2022-12-10 20:48 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        if shift.status in (Shift.Status.CANCELING, Shift.Status.FINISHED):
Правильное название статуса cancelled. Это ошибка в моделе.

2022-12-10 20:48 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +            raise HTTPException(
Создай кастомные исключения и используй их. HTTP исключения неправильно использовать. Этот метод может использовать, например бот.

2022-12-10 20:48 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        update_shift_data = update_shift_data.dict(exclude_unset=True)
Не надо выполнять преобразование в словарь. С объектами работать намного проще, удобнее и нагляднее.
```suggestion
        shift: Shift = await self.__shift_repository.get(id)
        if shift.status in (Shift.Status.CANCELING, Shift.Status.FINISHED):
            raise ...

        if shift.status == Shift.Status.STARTED:
            if update_shift_data.started_at:
                raise ...

        if update_shift_data.started_at and not update_shift_data.finished_at:
            if update_shift_data.started_at >= shift.finished_at:
                raise ...
            shift.started_at = update_shift_data.started_at

        if not update_shift_data.started_at and update_shift_data.finished_at:
            if shift.started_at >= update_shift_data.finished_at:
                raise ...
            shift.finished_at = update_shift_data.finished_at

        if update_shift_data.title:
            shift.title = update_shift_data.title
        if update_shift_data.final_message:
            shift.final_message = update_shift_data.final_message

        return await self.__shift_repository.update(id, shift)
```

2022-12-10 20:48 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        update_shift_data = update_shift_data.dict(exclude_unset=True)
Последние проверки и присвоения можно заменить на тернальный оператор, но это дело вкуса: 
        shift.title = update_shift_data.title if update_shift_data.title else shift.title

2022-12-10 20:49 UTC, ADesBiysk commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
Задача была оформлена, но не распределена. 
https://www.notion.so/Refactoring-update_shift-03d1ee2e2b284c83afd419cde7bd142a
Запиши её себе.

2022-12-11 00:57 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +        return values
Я это понимаю так: Если есть значение у даты старта и финиша, то провалидировать значения, если хотя бы одного или обоих нет, то ничего не нужно делать.
Как-то это не правильно!
Давайте все поля вообще сделаем обязательными! Тогда не будет каких-то странных манипуляций для валидации значений перед сохранением. Апи отдаёт на фронт последнее состояние, а мы ожидаем его получить в ответ. Тем более, это именно так и будет, так как мы договаривались применять изменения только по нажатии на кнопку сохранить, а при этом будет отправляться вся форма. Автосохранения не будет и это глупо предусматривать возможность для этого.
@ADesBiysk

2022-12-11 10:54 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
Забрал себе задачу, добавил проверки описанные в ней. Длину названия смены сделал 100 символов (как в модели models.py), теперь везде одинаково.

2022-12-11 10:57 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +        shift = await self.__shift_repository.get(id)
Заменил. Теперь работает как надо. Правда из-за абстрактности не понятно, какой именно объект какой модели запрашивается, поэтому передаю туда object_name='в запросе'. Чтобы ответ был "Объект в запросе с id ..."

2022-12-11 10:57 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +        if shift.status in (Shift.Status.CANCELING, Shift.Status.FINISHED):
Поправил в модели и у себя.

2022-12-11 10:58 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +            raise HTTPException(
Сделал пока одно кастомное для всех трёх случаев, в которых оно выбрасывается. Вручную прописал тексты ошибок при вызове.

2022-12-11 10:59 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +        update_shift_data = update_shift_data.dict(exclude_unset=True)
Теперь все поля обязательные (см. коммент Антона ниже), и всё немного по другому:)

2022-12-11 11:05 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +        return values
Сделал все поля обязательными. Правда теперь из-за того, что поле started_at обязательное...то всегда вызывается валидатор validate_started_later_than_now и он не даст изменять никакие смены из прошлого, в том числе и текущую смену...её дата начала тоже окажется в прошлом через день после запуска.
Причем этот валидатор всё ещё нужен, когда мы хотим изменить смену со статусом preparing, например.

2022-12-11 11:08 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +        return values
Есть предложение перенести эту валидацию в метод обновления смены. Там проверять дату начала нужно будет только при изменении смены со статусом preparing, у других смен ее и так нельзя будет поменять.

2022-12-11 11:10 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +        return values
А в ShiftUpdateRequest'e выключить её:
    @validator("started_at")
    def validate_started_later_than_now(cls, value: datetime) -> datetime:
        pass

2022-12-11 18:26 UTC, ADesBiysk commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
Длина названия должна быть от 3 до 60 символов. Дополнил задачу.

2022-12-11 19:04 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +        return values
Да, правильнее перенести эту валидацию в сервис или в метод. Там её место. Тут валидируем какие-то очень базовые вещи, если не получается провалидировать, то выносим туда.

2022-12-11 19:46 UTC, ADesBiysk commented on src/api/request_models/shift.py
> +    title: str = Field(..., max_length=100)
Длина названия от 3 до 60. Обновил задачу.

2022-12-11 19:46 UTC, ADesBiysk commented on src/core/db/models.py
> +        CANCELLED = "cancelled"
Нужна миграция.

2022-12-11 19:46 UTC, ADesBiysk commented on src/core/exceptions.py
> +from http import HTTPStatus
Если работаешь на linux или mac, то надо сделать вот это: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings
измени его и попробуй загрузить заново. Без подсветки изменений сложнее делать ревью.

2022-12-11 19:46 UTC, ADesBiysk commented on src/api/request_models/shift.py
>      started_at: datetime
Нам важна только дата, время не учитываем. Поэтому логичнее сделать тип date. Тогда не нужно будет выполнять преобразование в дату при каждом сравнении.

2022-12-11 19:46 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +                shift.started_at != update_shift_data.started_at.date()
Я бы эти условия вынес в переменные и использовал any(...).

2022-12-11 19:46 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        return await self.__shift_repository.update(id, Shift(**update_shift_data.dict()))
Нужно изменять полученный объект, и его обновлять, а не создавать новый.

2022-12-11 20:02 UTC, AntonZelinsky requested changes

2022-12-11 20:02 UTC, AntonZelinsky commented on src/core/db/models.py
> +        CANCELLED = "cancelled"
Миграцию нужно добавить

2022-12-11 20:02 UTC, AntonZelinsky commented on src/core/db/repository/abstract_repository.py
> +            raise NotFoundException(object_name='в запросе', object_id=id)
И что это получится? `"Объект в запросе с id: 123 не найден.`?
`self.detail = "Объект {} с id: {} не найден".format(object_name, object_id)`
Давай, хотя бы, передавать имя модели `_model` не найден, чтобы красивее и понятнее было.

2022-12-11 20:02 UTC, AntonZelinsky commented on src/core/exceptions.py
> +    def __init__(self, object_name: str, object_id: UUID):
Так перекрашиваться не должно! 
![image](https://user-images.githubusercontent.com/1431279/206924209-1934ff01-4720-45ed-9d4b-3233d7bed24b.png)


Спрашивается, стоит ли у тебя прекомит, который должен исправлять концовки файлов? Проверь, пожалуйста.
@ADesBiysk сделай, пожалуйста, пост в общем чатике, чтобы все себе установили прекомит и убедились, что работа ведётся именно через него.
![image](https://user-images.githubusercontent.com/1431279/206924412-4de32b77-36ee-44cc-86b5-d7dec4dc00bb.png)

2022-12-11 20:02 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="В закончившейся или отмененной смене можно изменить только название")
1. в этом случае два if можно объединить.
2. тут не нужен второй if, если смена завершённая, её нельзя менять
3. что-то не сходится с твоим предыдущим комментом

> ![image](https://user-images.githubusercontent.com/1431279/206924687-620918d1-f777-48ac-a408-7425c320958e.png)

2022-12-11 20:02 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="Нельзя установить дату окончания текущей смены прошедшим числом")
К этой валидации есть несколько вопросов. 
В принципе, всю валидацию смен давайте перенесём из валидаторов в сервисы или модели. Я попробую перечислить все правила:
1. Дата начала смены не может быть меньше текущей.
2. Дата начала смены не может быть больше или равняться дате окончания.
3. Дата начала смены не может быть в прошлом.
3.1. Дата начала запушенной смены не может быть изменена.
4. Дата окончания смены не может быть больше 4-х месяцев.
5. Дата окончания смены не может быть в прошлом.

Под каждое из правил нужно создать валидатор, а потом, объединить их для создания и обновления в обобщающие функции. Эти функции должны принимать 1 или 2 аргумента, в зависимости от необходимости, если будет передаваться существующая модель, то она должна идти первым аргументом. Как итог, тут и при создании будет вызов одной функции для валидации. Функция валидации (внутри основной) так же должна быть и для попытки изменить существующие смены.

Кажется, что это не все правила. Если я что-то упустил, то просьба написать, я дополню список, а потом перенесём его в документацию.

2022-12-11 20:02 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +        return await self.__shift_repository.update(id, Shift(**update_shift_data.dict()))
Вся же эта переделка затеивалась для того, чтобы избавиться от этого 💩 `Shift(**update_shift_data.dict())`.
Добавь, пожалуйста, замечания об этом в кодстайл нашей ВиКи и сделай пост в общем канале, что так сохранять код нельзя. Только передавая полный объект. И попроси всех перечитать эту ВиКи, там много чего полезного!
```suggestion
        return await self.__shift_repository.update(id, shift)
```

2022-12-12 02:56 UTC, ADesBiysk commented on src/core/exceptions.py
> +    def __init__(self, object_name: str, object_id: UUID):
Написал.

2022-12-12 03:28 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        return await self.__shift_repository.update(id, Shift(**update_shift_data.dict()))
Кратко написал: https://www.notion.so/codestyle-fc03c29c1edf4df7a335727efb5cc075#791ceeb0a8b44bd0afab41685a8ebe5a

2022-12-12 08:53 UTC, Alexey-Bormotov commented on src/core/exceptions.py
> +    def __init__(self, object_name: str, object_id: UUID):
Да, прекоммит стоит, всё проверят, исправляет сам, если надо. В первый раз такая "перекраска" случилась. Проверю ещё, может что сломалось.
![Снимок экрана от 2022-12-12 15-52-29](https://user-images.githubusercontent.com/89861426/207002329-a5c6cdcd-a922-46b8-928b-8700a8edab9f.png)

2022-12-12 08:59 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="В закончившейся или отмененной смене можно изменить только название")
Это я взял из новой задачи: https://www.notion.so/Refactoring-update_shift-03d1ee2e2b284c83afd419cde7bd142a
How To Do? (2 пункт задачи)
Перед изменением атрибутов смены нужно внести следующие проверки:
1. Если смена запустилась, то нельзя редактировать дату старта.
2. Если финишировала, то **_нельзя редактировать ничего кроме названия_**.
3. У запущенной смены нельзя дату финиша сделать уже прошедшим числом.

2022-12-12 09:07 UTC, Alexey-Bormotov commented on src/core/db/models.py
> +        CANCELLED = "cancelled"
Пробовал, генерируется пустая миграция... Убрал её пока, не стал коммитить.
![Снимок экрана от 2022-12-12 16-05-33](https://user-images.githubusercontent.com/89861426/207005247-01d65857-8f05-4970-9db7-4be97cf6ca8b.png)

2022-12-12 09:08 UTC, Alexey-Bormotov commented on src/core/db/models.py
> +        CANCELLED = "cancelled"
Пробовал, генерируется пустая миграция... Убрал её пока, не стал коммитить. (Скриншот ниже, в комменте Антона с тем же замечанием)

2022-12-12 10:18 UTC, ADesBiysk commented on src/core/db/models.py
> +        CANCELLED = "cancelled"
Да. Посмотрел внимательнее. Мы изменяем значение, в которое преобразуется значение из БД. Поэтому и миграция пустая. 
Миграция не нужна.

2022-12-12 10:22 UTC, ADesBiysk commented on src/core/exceptions.py
> +    def __init__(self, object_name: str, object_id: UUID):
Посмотрел текущий файл из репозитория. Проблема в нём. Твой PR должен привести его в порядок.

2022-12-12 10:22 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
А в модели нужно будет добавить constraint на минимальную длину?
 ```
__table_args__ = (
        CheckConstraint('char_length(title) > 2',
                        name='_title_min_length_сс'),
    )
```

2022-12-12 10:24 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="В закончившейся или отмененной смене можно изменить только название")
Давай ориентироваться на комментарий ниже, со списком всех условий. Лучше здесь все их обсудить, а потом конечный вариант добавить в задачу, чтобы QA знали какие условия проверять.

2022-12-12 10:47 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +    title: str = Field(..., max_length=100)
А в модели нужно будет добавить constraint на минимальную длину?
table_args = (
CheckConstraint('char_length(title) > 2',
name='title_min_length'),
)

2022-12-12 11:02 UTC, Alexey-Bormotov commented on src/core/exceptions.py
> +from http import HTTPStatus
Я на Linux. Сделал. В конфиге добавился параметр. Посмотрим как будет.

2022-12-12 11:03 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +        return await self.__shift_repository.update(id, Shift(**update_shift_data.dict()))
Почитал сегодня codestyle, переделаю. Теперь ясно, как надо)

2022-12-12 12:06 UTC, Alexey-Bormotov commented on src/core/db/repository/abstract_repository.py
> +            raise NotFoundException(object_name='в запросе', object_id=id)
Сделал: raise NotFoundException(object_name=self._model.__name__, object_id=id). Так и правда лучше:)

2022-12-12 12:15 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +        return await self.__shift_repository.update(id, Shift(**update_shift_data.dict()))
Исправил.

2022-12-12 12:16 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
>      started_at: datetime
Сделал.

2022-12-12 14:40 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="Нельзя установить дату окончания текущей смены прошедшим числом")
Дата окончания не может быть больше 4-х месяцев от даты начала?...Или от текущей даты? Есть валидатор, который проверяет дату окончания от текущей даты. Т.е. по сути нельзя создать смену на будущее.
Допустим мы решили устроить каникулы на 3 месяца, но при этом создать смену заранее (на будущее), а нам валидатор не даст такое сделать. `if finished_at > (date.today() + timedelta(days=120))`

Или смысл этого валидатора в том, чтобы смена не была больше 4 месяцев? тогда нужно валидировать от даты начала смены, а нет от даты сегодняшнего дня.

2022-12-12 14:51 UTC, Alexey-Bormotov commented
Сделал коммит, пока миграцию не создавал. Вдруг ещё что-то потребуется добавить.

2022-12-12 15:03 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +            raise ValueError("Нельзя изменять даты начала и окончания отдельно друг от друга")
Сделал валидацию на уровне модели, но без миграции пока.

2022-12-12 15:03 UTC, Alexey-Bormotov commented on src/api/request_models/shift.py
> +    title: str = Field(..., max_length=100)
Сделал валидацию на уровне модели, но без миграции пока.

2022-12-12 22:36 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +    title: str = Field(..., max_length=100)
Констрейн не имеет смысла, если длинна колонки в базе будет чётко задана

2022-12-12 22:38 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="Нельзя установить дату окончания текущей смены прошедшим числом")
От даты старта, проверяется длинна смены. 
Давай перефразируем:
4. Длинна смены не может быть больше 4-х месяцев.

2022-12-12 23:00 UTC, AntonZelinsky approved these changes
Супер, осталось совсем чуть-чуть

2022-12-12 23:00 UTC, AntonZelinsky commented on src/core/exceptions.py
> +        self.status_code = HTTPStatus.FORBIDDEN
Давай лучше бэд реквест. Создавать можно, а вот аргументы пришли некорректные.

2022-12-12 23:00 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +            raise ShiftUpdateException(detail="Нельзя изменить завершенную или отмененную смену")
А тут подойдёт статус форбиден. Так как именно запрещено.
Предлагаю отнаследоваться от этого исключения и сделать его с правильным статусом — `UpdateShiftForbiddenException`.
Кстати, я забыл прошлы раз напистаь, тут неправильный порядок слов в предложении. Звучит так, как будто `проблемы у смены обновления`, а не `при обновлени смены`. Порядок слов очень важен! Учите английский!
`UpdateShiftException` — Само название исключения очень плохое, не показывает в чём конкретно проблема, но наверно, пусть остаётся пока так, потом подумаем над более красивым вариантом.

2022-12-12 23:00 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +            self.check_started_and_finished_dates(update_shift_data.started_at, update_shift_data.finished_at)
А теперь, создай отдельную функцию и помести в неё всё это содержимое, чтобы тут был всего один вызов для обновления  и подобный для создания.

2022-12-12 23:01 UTC, AntonZelinsky commented on src/core/services/shift_service.py
> +            self.check_started_and_finished_dates(update_shift_data.started_at, update_shift_data.finished_at)
Если эти функции используются только тут, то они должны быть приватными!

2022-12-13 08:31 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +                raise ShiftUpdateException(detail="Нельзя установить дату окончания текущей смены прошедшим числом")
Вот так понятнее, и логичнее) А то было странно, почему в бывшем валидаторе 4 месяца отсчитывалось от сегодняшнего дня, а не от даты старта.

2022-12-13 08:47 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +            raise ShiftUpdateException(detail="Нельзя изменить завершенную или отмененную смену")
Может `UpdateShiftRequestException` подойдет? Вместо `ShiftUpdateException`

2022-12-13 10:53 UTC, Alexey-Bormotov commented
Залил изменения. 
1. Убрал constraint из модели.
2. Миграцию пока не делал, т.к. там опять проблема с двумя головами.
3. Для создания и изменения смены сделал одну функцию валидации. Так пойдет? Или лучше сделать разные для создания и для изменения?
4. Добавил докстринги.

2022-12-13 18:33 UTC, ADesBiysk approved these changes
Косметические замечания. И обрати внимание на конфликты.

2022-12-13 18:33 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        if shift.status in (Shift.Status.CANCELLED, Shift.Status.FINISHED):
Эту проверку лучше сделать первой. При выполнении условия все остальные действия не имеют смысла.

2022-12-13 18:33 UTC, ADesBiysk commented on src/core/services/shift_service.py
> +        if not update_shift_data:
Здесь нужен комментарий. Не очень очевидное действие.

2022-12-14 05:49 UTC, Alexey-Bormotov commented on src/core/services/shift_service.py
> +        if shift.status in (Shift.Status.CANCELLED, Shift.Status.FINISHED):
Точно) сразу не обратил внимание.
Про конфликты да, вижу что девелоп ушла вперёд + жду когда там с миграциями всё наладится. Кстати уменьшение длины названия смены до 60 символов (в модели) другой человек делает, так что у себя уберу. Миграция не потребуется.

2022-12-14 13:54 UTC, merged