Feature/admin auth method
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #163
Opened 2022-12-26 14:06 UTC by Ivan-Skvortsov

ПР по задаче: https://www.notion.so/API-9fcdaeb9dd594dd4902805862eb18fc1

1. Создал модель Administrator
2. Создал эндпойнты для создания администратора, логина и получения информации об администраторе (для теста авторизации).
3. Соответственно, добавил pydantic-модели, сервис и репозиторий.

Проверил руками - работает. Единственно, в сваггере не работает встроенная кнопка авторизации (там отдается x-www-form-urlencoded, а у нас json). Но если делать запросы руками (через постман, например), то авторизация работает.

P.S.: обновление access токена при помощи refresh токена не делал. Нужна доп. инфа, как мы это будем реализовывать. Насколько я понимаю, refresh должен быть одноразовым, т.е. нам нужно хранить его на сервере.
Ну и в целом, ПР чересчур разросся уже =/

2022-12-26 22:48 UTC, AntonZelinsky requested changes
Вообще, задача требует доработки с точки зрения постановки задачи.
Во-первых, тут нет регистрации. Админ может приглашать других админов на специальной странице, заполнив поле имени, фамилии и почты. Дальше эта информация заносится в базу данных и отправляется письмо на почту. перейдя по ссылке с почты, продолжается регистрация участником, от может отредактировать имя и фамилию и установить пароль. на этом регистрация заканчивается.
@ADesBiysk даже таблицы к базе рисовал и мы их согласовывали. Трясите его, чтобы задание переделал)

2022-12-26 22:48 UTC, AntonZelinsky commented on src/application.py
> +    administrator_router,
Как насчёт того, чтобы импортировать один роутер, а потмо просто из него брать все роутеры его модуля.

2022-12-26 22:48 UTC, AntonZelinsky commented on src/core/db/models.py
> +        ADMINISTRATOR = "administrator "
пробел

2022-12-26 22:48 UTC, AntonZelinsky commented on src/core/db/migrations/versions/2022-12-25_23.10.52_created_administrator.py
> +    sa.Column('status', sa.Enum('active', 'blocked', name='administrator_status'), nullable=False),
У нас раньше енамы как-то сложнее создавались, нежели ты сейчас делаешь, это точно норм?

2022-12-26 22:48 UTC, AntonZelinsky commented on src/core/settings.py
> +    SECRET_KEY: str
Если значение не было передано, то генерь рандомныую строку uuid например

2022-12-26 22:48 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +            raise AdministratorAlreadyExistException()
Исключение перенеси в репозиторий.

2022-12-26 22:48 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +        new_administrator["role"] = role
Забудьте про работу со словарями, зачем эти костыли? Слышали про ООП?

У AdministratorCreateRequest сделай метод создающий сущность Administrator. И там так же работай с объектами. И статус по дефолту там присваивай как активный.
Правда я пока не разобрался с регистрацией админов...(

2022-12-26 22:48 UTC, AntonZelinsky commented on pyproject.toml
> +email-validator = "^1.3.0"
Кажется, что нигде не используется, или его пидантик использует?

2022-12-29 19:49 UTC, Ivan-Skvortsov commented on pyproject.toml
> +email-validator = "^1.3.0"
Email-валидатор используется в типе `EmailStr` пидантика
https://docs.pydantic.dev/usage/types/#pydantic-types

2022-12-29 20:02 UTC, Ivan-Skvortsov commented on src/core/services/administrator_service.py
> +            raise AdministratorAlreadyExistException()
Но ведь у нас этот метод (`get_by_email_or_none`) используется в двух противоположных кейсах: 

- при регистрации нового пользователя мы проверяем, что пользователь не существует (в этом случае бросаем исключение, если метод возвращает значение, т.е. пользователь уже зарегестрирован)
- при аутентификации по токену (в этом случае бросаем исключение, если метод возвращает None, т.е. пользователь не существует).

Т.е. если его переносить в репозиторий - то нужно в репозитории делать два дополнительных метода.
Или так будет правильнее, с точки зрения архитектуры?

2022-12-29 20:31 UTC, Ivan-Skvortsov commented on src/core/db/migrations/versions/2022-12-25_23.10.52_created_administrator.py
> +    sa.Column('status', sa.Enum('active', 'blocked', name='administrator_status'), nullable=False),
Это алембик так нагенерировал. 
Но вообще да, раньше создавались типы конкретно для постгрес и при downgrad'e дропались эти типы.
У нас в вики написано, что миграции мы руками не трогаем, только по согласованию с лидами) Так что если согласовываете - поправлю по аналогии с предыдущими миграциями.
Как-то вот так:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/83599925/210008232-862d3af3-6092-4d41-88a0-7249ab0025a7.png">

2022-12-29 20:57 UTC, AntonZelinsky commented on src/core/db/migrations/versions/2022-12-25_23.10.52_created_administrator.py
> +    sa.Column('status', sa.Enum('active', 'blocked', name='administrator_status'), nullable=False),
Да уж, в вики написано всё правильно, только там этот кейс не предусмотрен. 
Но вообще, в чём разница? твой вариант будет строку хранить, а второй создаст тип в бд? 

Возникает вопрос, почему изначально отказались от твоего варианта?
Я не против его, но хотелось бы понять причины.

2022-12-29 21:03 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +            raise AdministratorAlreadyExistException()
Не, ты прав, это я не туда посмотрел.

2022-12-30 06:23 UTC, ADesBiysk reviewed
Схема БД нарисована и эти таблицы находятся ниже основной. Пока не объединял их. Первоначально мы обсуждали, что нужно разделить задачу на несколько отдельных:
1. Создание модели Administrator администратора и авторизация.
2. Создание модели AdministratorMailRequest. Разработка метода отправки приглашения н регистрацию.
3. Регистрация администратора, поскольку для этой задачи требуются готовые 2 таблицы.

Поэтому непосредственно регистрацию лучше здесь не делать.

@Ivan-Skvortsov Подскажи почему решил не использовать библиотеку https://fastapi-users.github.io/fastapi-users/10.2/

Refresh token хранить на сервере не нужно. Если бы его можно было подделать, то смысла в них не было.

2022-12-30 10:14 UTC, Ivan-Skvortsov commented
> 1. Создание модели Administrator администратора и авторизация.

Я сейчас ограничиваюсь этим пунктом, верно?


> @Ivan-Skvortsov Подскажи почему решил не использовать библиотеку https://fastapi-users.github.io/fastapi-users/10.2/

Эта библиотека создает дополнительные поля в модели пользователя: [is_active, is_superuser, is_verified](https://github.com/fastapi-users/fastapi-users-db-sqlalchemy/blob/686172c77932534e0c78d4b3b7937c997675da9b/fastapi_users_db_sqlalchemy/__init__.py#L29). У нас в схеме БД их нет, поэтому решил её не использовать) Но если это ок - то конечно, с библиотекой будет проще. Готов переделать.
 
> Refresh token хранить на сервере не нужно. Если бы его можно было подделать, то смысла в них не было.

Но ведь тогда мы не сможем проверить, пользовались рефреш токеном или нет. И если злоумышленник завладел рефреш токеном, то он получит доступ к сайту на неограниченное время (даже если пользователь токены обновит) - т.е. просто будет периодически запрашивать пару access-refresh.
А если токен будет храниться на сервере - тогда мы сможем проверить, пользовались им или нет. Т.е. получится два варианта:

- пользователь обновит рефреш, старый станет невалидным и злоумышленник потеряет доступ к сайту
- злоумышленник обновит рефреш, тогда пользователь потеряет доступ по токену, залогинится по email-паролю, соответственно обновит токены и злоумышленник потеряет доступ

Т.е. время, на которое злоумышленник получит доступ к сайту, будет ограничено временем жизни access токена.
В этом же и суть реферш токена?

Или я ошибаюсь?

2022-12-30 10:18 UTC, Ivan-Skvortsov commented on src/core/db/migrations/versions/2022-12-25_23.10.52_created_administrator.py
> +    sa.Column('status', sa.Enum('active', 'blocked', name='administrator_status'), nullable=False),
Мне кажется, все таки в моем варианте алембик некорректно сгенерировал енамы. Как минимум - не создал команду на их удаление при даунгрейде.
Вот тут как раз это обсуждается: https://github.com/sqlalchemy/alembic/issues/278

2022-12-30 10:55 UTC, AntonZelinsky commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
Тред для обсуждения fastapi-user, чтобы не плодить на странице очень много сообщений, которые нельзя будет схлопнуть потом @Ivan-Skvortsov @ADesBiysk.

2022-12-30 11:09 UTC, AntonZelinsky commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
> та библиотека создает дополнительные поля в модели пользователя: [is_active, is_superuser, is_verified](https://github.com/fastapi-users/fastapi-users-db-sqlalchemy/blob/686172c77932534e0c78d4b3b7937c997675da9b/fastapi_users_db_sqlalchemy/__init__.py#L29).
Ну, не используй тогда эту модель, там же можно полностью кастомную модель подставить. Да и плюс айдишки хотелось бы интом делать, а там выбора нет.

> если злоумышленник завладел рефреш токеном
А если он завладеет пальцами владельца этого токена, то можно их начать ломать, чтобы получить доступ к сайту и начать всем одобрять отчёты!

> получит доступ к сайту на неограниченное время
Рефреш токен имеет своё время жизни, его обычно делают длиннее чем у эксес токена на какое-то время, но всё равно, оно ограничено. + когда приходит запрос на обновление токена, нужно проверять статус пользователя и не давать просто так.

Ходить каждый раз в базу за токеном очень дорого по времени, запрос будет выполняться в раза два дольше, вариант, ходить в редис за ним, но нам не нужен такой высокий уровень безопасности. Мы ограничиваем время жизни токена и время жизни рефреш токена, этого нам достаточно. Так сделано на подавляющем большинстве сайтов и этого вполне хватает. 
Не нужно придумывать то, что не требуется клиентами. Как и защита от брутформа, идея хорошая, но до MVP и полноценного релиза мы даже не будем думтаь про такие штуки.
К тому же, это не публичный сайт.

2022-12-30 11:33 UTC, Ivan-Skvortsov commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
> Не нужно придумывать то, что не требуется клиентами. Как и защита от брутформа, идея хорошая, но до MVP и полноценного релиза мы даже не будем думтаь про такие штуки. К тому же, это не публичный сайт.

Да, точно, это я закапываться начал уже) Надо чаще напоминать себе, что основная цель работы - удовлетворение потребностей бизнеса, а не само написание кода)

> Да и плюс айдишки хотелось бы интом делать, а там выбора нет.

Почему, можно сделать и инты, как-то вот так: `User(SQLAlchemyBaseUserTable[int], Base)`, но опять же с доп. полями. Просто мы в проекте везде переиспользуем класс `Base`, в котором айдишник определен как uuid4. 
Кстати, может действительно использовать модели из fastapi-users? Поменять схему БД:  вместо енамов использовать предложенные поля. Т.е. `role` заменить на `is_superuser`, `status` на `is_active`, а `is_verified` делать по умолчанию False, и переводить в True после того, как пользователь воспользовался приглашением и обновил данные. По сути у нас в енамах по 2 значения, тот же самый bool)

2022-12-30 12:57 UTC, AntonZelinsky commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
Блин, предыдущее сообщение было не отформатировано, глянь ещё раз.

> в котором айдишник определен как uuid4

Видно, это я затупил. Тогда тут тоже.

> Поменять схему БД

Так, а почему бы не заменить полностью модель?

2022-12-30 13:31 UTC, Ivan-Skvortsov commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
Окей) Давайте подытожим тогда:
1. Делаю в объеме 

> Создание модели Administrator администратора и авторизация.

2. Переделываю все под использование `fastapi-users`, с кастомной моделью администратора
3. С токенами не заморачиваюсь, просто отдаю оба юзеру
4. Енамы в миграции правлю руками

Вроде бы ничего не упустил?

2022-12-30 14:02 UTC, AntonZelinsky commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
Насчёт третьего пункта не уверен))) 
Я поковырял [документацию и эта библиотека добавляет](https://fastapi-users.github.io/fastapi-users/10.2/usage/routes/) в проект кучу различных апишек, штук 20 наверно, а нам из них кажется особо ничего не нужно. Только логин и забыл пароль апи и всё. Всё дело в нашем необычном воркфлове с приглашением и регистрацией по ссылке.

Вот, сейчас и думаю, что Вани первоначальный вариант может быть лучше, только нужно немного всё реорганизовать.

Я сначала заварил всю эту кашу, а потом пошёл на попятную)

2022-12-30 16:41 UTC, Ivan-Skvortsov commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
По идее, можно просто не добавлять в роутер ненужные АПИ, а добавить только [auth_router ](https://fastapi-users.github.io/fastapi-users/10.2/configuration/routers/auth/#setup)(login/logout) и [reset password router](https://fastapi-users.github.io/fastapi-users/10.2/configuration/routers/reset/#setup) (forgot-password/reset-password).

Правда, судя по докам, в библиотеке не реализованы refresh токены, это все равно придется делать руками)

2023-01-09 07:55 UTC, ADesBiysk commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
> 1. Делаю в объеме:
> Создание модели Administrator администратора и авторизация.
Да. Регистрация после приглашений.

> 2. Переделываю все под использование fastapi-users, с кастомной моделью администратора
Если нужно реализовывать refresh токены руками, то выигрыш от библиотеки не столь очевиден. 
Т.е. есть 2 варианта: 
А. реализовать с refresh токеном самим, но при этом не тянем багаж из библиотеки. 
Б. убирать refresh, делать дольше время жизни access (например, неделя, т.е. раз в неделю надо будет логиниться заново) и переделываем модели под библиотеку. 
Оба со своими недостатками, но с учётом того, что админка не публичная, то вариант А нам меньше связывает руки.

> 3. С токенами не заморачиваюсь, просто отдаю оба юзеру
Чтобы можно было заблокировать какой-нибудь refresh токен, нужно сначала понять, что кто-то пакостит и кто это делает. Для этого требуется детальная информация об активности не просто администраторов/психологов, а каждого авторизованного устройства, что у нас не предусмотрено (пока и, вероятнее всего, никогда). Без этого смысла нет. 

> 4. Енамы в миграции правлю руками
Да. Все так сделаны.

Новые вопросы:
5. Мы же не ограничиваем количество устройств с которых авторизован администратор? Тогда, нужна галочка "чужой компьютер", чтобы не давали refresh токен, а только короткий access.

2023-01-12 17:55 UTC, ADesBiysk commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
@Ivan-Skvortsov Обсудили с Антоном и решили не использовать библиотеку.

2023-01-13 17:58 UTC, Ivan-Skvortsov commented on pyproject.toml
> +python-jose = {extras = ["cryptography"], version = "^3.3.0"}
Поправил миграции. Удалил код, связанный с созданием администратора.
Пока не понимаю, куда дальше двигаться)

2023-01-14 08:30 UTC, ADesBiysk approved these changes

2023-01-14 08:30 UTC, ADesBiysk commented on pyproject.toml
> +passlib = {extras = ["bcrypt"], version = "^1.7.4"}
Не забывай добавлять библиотеки в requirements.txt

2023-01-14 08:30 UTC, ADesBiysk commented on src/api/routers/administrator.py
> +        return await self.administrator_service.get_access_and_refresh_tokens(auth_data)
Не очень удачное название функции.

2023-01-14 08:30 UTC, ADesBiysk commented on src/core/services/administrator_service.py
> +        return PASSWORD_CONTEXT.hash(password)
Можно посолить.

2023-01-14 08:30 UTC, ADesBiysk commented on src/core/db/models.py
> +    last_logined_at = Column(TIMESTAMP)
Мне кажется, что по-английски будет правильнее last_login_at. Если согласен, то давай исправим.

2023-01-14 08:30 UTC, ADesBiysk commented on src/core/services/administrator_service.py
> +        return TokenResponse(**tokens)
Можно и без промежуточного словаря.
```suggestion
        return TokenResponse(
            access_token = self.__create_jwt_token(subject, ACCESS_TOKEN_EXPIRE_MINUTES),
            refresh_token = self.__create_jwt_token(subject, REFRESH_TOKEN_EXPIRE_MINUTES),
        )
```

2023-01-14 08:30 UTC, ADesBiysk commented on src/core/services/administrator_service.py
> +        raise UnauthorizedException()
AdministratorBlockedException()?

2023-01-14 16:09 UTC, Ivan-Skvortsov commented on src/core/services/administrator_service.py
> +        return PASSWORD_CONTEXT.hash(password)
Он тут уже солёный) 
https://passlib.readthedocs.io/en/stable/faq.html#:~:text=will%20automatically%20generate%20a%20salt%2C%20and%20include%20it%20as%20part%20of%20the%20hash%20that%E2%80%99s%20returned

2023-01-19 21:23 UTC, AntonZelinsky approved these changes

2023-01-19 21:23 UTC, AntonZelinsky commented on src/api/routers/__init__.py
> +from src.api.routers.hello import TELEGRAM_WEBHOOK_ENDPOINT, webhook_router  # noqa
hello??

2023-01-19 21:23 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +    token: str = Depends(OAUTH2_SCHEME), administrator_service: AdministratorService = Depends()
не, делай нормально, как метод сервиса.

2023-01-19 21:23 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +        email = payload.get("sub")
Почему емаил это sub? Вроде емаил это емаил. Так же не обязательно должна называться переменнаяя, или я не прав?

2023-01-19 21:23 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +        raise UnauthorizedException()
Делать это нужно не тут, а в отдельном методе репозитория, посмотри как сделано в методе `AbstractRepository.get`.
И зачем делать отдельный метод `administrator_service.get_administrator_by_email`, который просто вызывает репозитоирий?

2023-01-19 21:23 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +        raise UnauthorizedException()
А почему `UnauthorizedException`, а не нот фаунд, например?

2023-01-19 21:23 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[ALGORITHM])
по идее, при декоде не нужен сикрет кий, ты можешь в любом онлайн декодере расшифровать любой jtw токен и узнать что внутри

2023-01-19 21:23 UTC, AntonZelinsky commented on src/core/services/administrator_service.py
> +    token: str = Depends(OAUTH2_SCHEME), administrator_service: AdministratorService = Depends()
`Depends(OAUTH2_SCHEME)` получать во вьюшке, а сюда передавать просто токен

2023-01-19 21:23 UTC, AntonZelinsky commented on src/api/routers/administrator.py
> +        return current_active_admin
Эта функция находится в сервисе, предлагаю, классическим методом и вызывать функцию, чтобы получать ответ из неё

2023-01-19 21:23 UTC, AntonZelinsky commented on src/api/routers/administrator.py
> +        return await self.administrator_service.get_tokens(auth_data)
Предлогаю создать аутентификейт сервис и метод логин, гет юзер, чтобы аутентификация (работа с токенами) была в одном месте. А администратор_сервис оставить для работы с администраторов со своим профилем, например, с обновлением его, установкой пароля, блокировкой и разблокировкой.

2023-01-20 08:41 UTC, Ivan-Skvortsov commented on src/api/routers/__init__.py
> +from src.api.routers.hello import TELEGRAM_WEBHOOK_ENDPOINT, webhook_router  # noqa
Это не мои изменения, модуль с таким болтается еще со старта проекта) Сейчас переименую

2023-01-20 08:56 UTC, Ivan-Skvortsov commented on src/core/services/administrator_service.py
> +        email = payload.get("sub")
Нет, ты прав. Это только [рекомендованное ](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.2)название. Исправил 👍

2023-01-20 09:09 UTC, Ivan-Skvortsov commented on src/core/services/administrator_service.py
> +        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[ALGORITHM])
Секрет нужен для верификации сигнатуры. Ну т.е. чтобы убедиться, что токен не был изменён или подделан

2023-01-20 11:04 UTC, Ivan-Skvortsov commented on src/core/services/administrator_service.py
> +        raise UnauthorizedException()
> А почему `UnauthorizedException`, а не нот фаунд, например?

Подразумевается, что этот метод будет использоваться для доступа к ресурсам, требующим аутентификации (в качестве депенденси)
Поэтому, если по токену нельзя установить пользователя - бросаем unauthorized. Логика такая)

2023-01-22 06:11 UTC, merged