registration process
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #20
Opened 2022-09-20 21:44 UTC by NikolaySolop

1) handler инициализации формы
2) метод определения url для инициализации формы (utils.py)
3) registration.html с передачей данных
4) метод регистрации

зависимые доработки:
5) схемы валидация на pydantic
6) базовый класс crud для моделей
7) корректировка .env и read.me

fix
8) в модели request shift_id атрибут nullable исправлен на True (смена назначается после заявки админом)
9) сделаны миграции после п.8

2022-09-25 06:47 UTC, petrovskydv requested changes, later dismissed

2022-09-25 06:47 UTC, petrovskydv commented on src/core/utils.py
> +    if d.get(settings.DEBUG.lower()):
это очень странная конструкция. 
settings.DEBUG должна иметь тип bool.

2022-09-25 06:47 UTC, petrovskydv commented on src/core/utils.py
> +    return get_production_url(file_name)
может стоит отказаться от двух разных методов? и брать url из переменных окружения.

2022-09-25 06:47 UTC, petrovskydv commented on src/html/registration.html
> +  <input type="text" id="date_of_birth" name="date_of_birth"><br>
нужно поменять тип на date

2022-09-25 06:47 UTC, petrovskydv commented on src/schemas/user.py
> +        return value
давай сделаем валидацию номера как [здесь](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/a359c6e481a235990a3ce0c874c959e592849d1b/src/core/db/models.py#L125-L132)

2022-09-25 20:09 UTC, AntonZelinsky requested changes

2022-09-25 20:09 UTC, AntonZelinsky commented on .gitignore
> +/migrations/versions/old/
А что это такое и почему не нужно вкомитывать такие миграции? Если это твои личные штуки, то добавь их в глобальных гит игнор, а игнор проекта не нужно захламлять

2022-09-25 20:09 UTC, AntonZelinsky commented on README.md
> +SERVER_URL=
[В другом ПРе добавили уже переменную для урла приложения, используй такю же. Сегодня/завтра тот ПР будет смержен.](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/feature/webhook_mode/.env.example#L8)

2022-09-25 20:09 UTC, AntonZelinsky commented on src/core/settings.py
> +    DEBUG: str
Так определись, флаг Дебаг — это строка или булеан? Сколько значений он может принимать?

2022-09-25 20:09 UTC, AntonZelinsky commented on src/core/utils.py
> +    return get_production_url(file_name)
На 100% согласен, для приложения нет разницы что за урл, он просто берётся из конфига. На проде тоже можно запустить приложение в режиме дебага.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/core/utils.py
> +    return get_production_url(file_name)
Как по мне, этот файл вообще нужно удалить, какая-то ерундень(

2022-09-25 20:09 UTC, AntonZelinsky commented on src/core/utils.py
> +        f"https://{settings.SERVER_URL}{BASE_DIR}"
[Вообще, урл включает в себя http.](https://en.wikipedia.org/wiki/URL). Зачем тут BASE_DIR? 
И как это вообще стыкуется с твоей задачей? Я проверял, там ничего такого вообще не было!!!

2022-09-25 20:09 UTC, AntonZelinsky commented on src/html/registration.html
> +  <input type="text" id="name" name="name"><br>
Давай на инпуты повесим аттрибут required, чтобы без заполненного поля форму не давало отправить.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/bot/handlers.py
> +    )
Давай это пока уберём. По хорошему, тут будет получение записи пользователя из базы и какая-то логика редактирования и повторной отправки заявки, но мы пока это не проговаривали, поэтому, не хочется писать заглушки, которые возможно потом не понадобятся.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/main.py
> +    bot_app.add_handler(CommandHandler('reg', registration_form_init))
[Посмотри наш код стайл документ](https://www.notion.so/codestyle-fc03c29c1edf4df7a335727efb5cc075), там описываются кейсы как называть функции. Придерживайся пожалуйста его.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/main.py
> +    bot_app.add_handler(CommandHandler('reg', registration_form_init))
Команда для тестирования не нужна! У нас есть простой воркфлов: пользователь нажимает кнопку старт бот, к нему приходит сообщение с инлайновой кнопкой, при нажатии на неё, должна отрабатывать эта функция, предлагая форму реггистрации.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/main.py
> +        MessageHandler(filters.StatusUpdate.WEB_APP_DATA, web_app_data))
Зачем ты переносишь всё на несколько строк? от этого же ухудшается читаемость кода!

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/user.py
> +        except ValidationError as error:
Функция называется date_parse, но это не какая-то общая функция, а валидация конкретной даты! Значит, функция должна называться соответственно. И название функции должно состоять из следущего паттерна `validate_названиеПоля`, так как со стороны, названия твоих функций выглядят как получение данных, а не их валидация. И добавь это правило в wiki, ссылку на которую я довал в этом ПРе.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/user.py
> +        except ValidationError as error:
Другой вопрос то, что нет смысла подключать библиотеку для парсинга, если она просто кидает исключение. Это делает и стандартная функция для парсинга. 
Другой вопрос, что это вообще может не понадобиться, если ты выполнишь все фидбеки выше, в частности, добавишь аттрибут reqired и сделаешь поле типа date. Тогда данные всегда будут приходить в этом поле и всегда будут валидными. Но доп валидация не помешает, так как тот кто захочет, наверняка сможет сломать приложение.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/user.py
> +            raise ValueError('Адрес содержит недопустимые символы')
А кто ревьювить себя будет? Пробегись ты глазами по коду, увидел бы множесто копипаста. Если на то пошло, то regex можно вынести к переменную файла, чтобы не задавать каждый раз.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/user.py
> +        return value
Что-то у меня смонения, там валидация будет на уровне orm, то есть, когда данные пройдут всю бизнес логику, а ведь на ней чаще всего и будут происходить ошибки. Например, если нам нужно будет отправлять смс (плохой пример, но другого у меня нет) и мы это будем делать до сохранения, то приложение будет падать в серсисе отправки смс.
Мораль такова, чем раньше происходит валидация, тем лучше.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/registration.py
> +    approved = 'approved'
Дубликат получается, мы [специально делали енамку](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/pull/20/files#diff-4f024c19320381ef47451713134029865cdd4ad4439a418c4c580212591e2956R136), чтобы её можно было использовать в приложении

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/registration.py
> +class RequestData(BaseModel):
[Обрати внимание на структуру папок. Тут есть для запросов и ответов специальные папки.](https://www.notion.so/02e8e349449f4b3fa564759942cbf73c)

2022-09-25 20:09 UTC, AntonZelinsky commented on src/schemas/user.py
> +    surname: str = Field(..., min_length=2, max_length=100)
А зачем тут `...`?

2022-09-25 20:09 UTC, AntonZelinsky commented on src/bot/handlers.py
> +                 f"вам придет уведомление",
Почему так много переносов? Кажется, я уже писал об этом, но всё же, меня это добивает.( Такое ощущение, что код пишется на смартфоне и для экраснов смартфонов.( 
Это же только ухудщает чиаемость.( 
Хочется оторвать руки...

![image](https://user-images.githubusercontent.com/1431279/192162944-2ec242b8-9166-4096-9470-a8a9d38a435d.png)

2022-09-25 20:09 UTC, AntonZelinsky commented on src/core/db/db.py
> -    )
То временное решение которое было раньше, немного лучше чем предложенное тобой, потому что есть какая-то функция отдающая сессию, но вы вынес создание сессии за её переделы и сам же функцию не вызвал. Смысл от неё сразу потерялся.

2022-09-25 20:09 UTC, AntonZelinsky commented on src/bot/services.py
> +    async with async_session() as session:
Хочу первый раз сделать тебе больно, по настоящему больно.))
Весь код с crud нужно удалить! 
Этот ПР стал очень большим и если ещё ту часть начать править, то мыы застрянем ещё на пару недель. У нас есть идея как сделать более правильно и может ты эту задачку и заберёшь, почитав парочку статей как это лучше сделать, но давай в твоей задаче оставим только форму и получение данных из неё. Пусть сервис остаётся, в него чуть позже добавим сохранение в базу.

2022-09-28 07:07 UTC, NikolaySolop commented on src/core/settings.py
> +    DEBUG: str
Отказался от переменной DEBUG совсем, так как далее был комментарий, что будем получать url до html формы на базе переменной окружения APPLICATION_URL

2022-09-28 07:12 UTC, NikolaySolop commented on src/core/utils.py
> +        f"https://{settings.SERVER_URL}{BASE_DIR}"
Уберу файл целиком.
Моя идея была, чтобы достать путь до 'registration.html' автоматически через функции, которые описаны выше в коде на случай, если структура проекта изменится и html форму перенесут в другое место.
Так как решено просто воспользоваться переменной окружения APPLICATION_URL и на основе ее 'руками' сделать путь до 'registration.html', этот файл теперь просто не нужен.

2022-09-28 07:16 UTC, NikolaySolop commented on src/core/utils.py
> +    if d.get(settings.DEBUG.lower()):
Если путь до registration.html строим на базе переменной окружения APPLICATION_URL, то необходимость в DEBUG режиме, на мой взгляд, отпадает. Этот блок будет удален вместе со всем файлом

2022-09-28 07:16 UTC, NikolaySolop commented on src/core/utils.py
> +    return get_production_url(file_name)
Файл будет удален

2022-09-28 07:18 UTC, NikolaySolop commented on .gitignore
> +/migrations/versions/old/
В следующем комите эти миграции уже были добавлены в gitignore

2022-09-28 07:19 UTC, NikolaySolop commented on README.md
> +SERVER_URL=
Ок, использую APPLICATION_URL

2022-09-28 07:24 UTC, NikolaySolop commented on src/bot/handlers.py
> +    )
ок, убираю

2022-09-28 21:11 UTC, NikolaySolop commented on src/bot/services.py
> +    async with async_session() as session:
ок, сервис оставляю, crud удаляю
у меня есть смежная [задача](https://www.notion.so/9e69947d892240079c2827e3caba4b5c) по методу регистрации. Мне в отдельном ПРе доделать или уже здесь все сделать, раз я в этом ПРе написал pydantic модели?

2022-09-28 21:11 UTC, NikolaySolop commented on src/main.py
> +    bot_app.add_handler(CommandHandler('reg', registration_form_init))
Я правильно понимаю, что я должен в хендлер [start](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/410f55de11f2664f3bd3ccf2e7cb5d4868013e8b/src/bot/handlers.py) добавить инлайновую кнопку с вызовом функции? обрабоку команды я убираю

2022-09-28 21:11 UTC, NikolaySolop commented on src/schemas/user.py
> +        return value
что здесь необходимо поправить? или нужно удалить валидация номера телефона?

2022-09-28 21:11 UTC, NikolaySolop commented on src/core/db/db.py
> -    )
здесь я не совсем понимаю, как делать запись данных в БД без доступа к async_session.
я работал с конструкцией
async with async_session() as session:
     [тут код записи в БД]

я понимаю, как использовать генератор get_session() в FastAPI через Depends, а как применить генератор без FastAPI  понимания нет

2022-09-30 10:00 UTC, AntonZelinsky commented on src/schemas/user.py
> +        return value
Тут нужно поправить только название метода, посмотри в кодстайле нашей вики, как правильно должны называться такие методы

2022-09-30 13:10 UTC, AntonZelinsky commented on src/bot/services.py
> +    async with async_session() as session:
Удали круды, закомитайся и смержи к себе последний дев, там есть репозиторий, в который нужно передавать содель пользователя. Сейчас, можешь спокойно сделать задачу до конца

2022-09-30 13:12 UTC, AntonZelinsky commented on src/core/db/db.py
> -    )
Как написал выше, удали круды, закомитайся, смержи к себе дев, там есть юзер репозиторий, который тебе нужно использовать для создания записей.

2022-09-30 16:48 UTC, Ivan-Skvortsov commented on src/core/db/db.py
> -    )
Мне кажется, тут вопрос в том, как использовать генератор сессий (`get_session()`) вне приложения FastAPI.
Т.е. как получить сессию в хендлере бота.

2022-09-30 19:39 UTC, NikolaySolop commented on src/core/db/repository/user_repository.py
> +        user = await self.session.execute(select(User).where(attr == attr_value))
Здесь нужна помощь. На этой строчке выдает ошибку при попытке записи данных в БД.
"AttributeError: 'Depends' object has no attribute 'execute'"
Как я понимаю, при работе через FastAPI проблем нет, фреймворк достает сессию из генератора и с ней дальше работает. Если же мы напрямую пытаемся взаимодействовать с БД без FastAPI вместо self.sesssion у нас объект Depends. Различные попытки после долгого прочтения stackoverflow достать сессию к успеху не привели.

2022-09-30 19:39 UTC, NikolaySolop commented on src/schemas/user.py
> -import re
перенес в src/api/request_models

2022-09-30 19:39 UTC, NikolaySolop commented on src/schemas/registration.py
> -from enum import Enum
перенес в src/api/request_models

2022-09-30 19:39 UTC, NikolaySolop commented on src/bot/services.py
> -async def registration(user_data):
перенес в src/core/services

2022-10-01 16:09 UTC, NikolaySolop commented on src/bot/handlers.py
> +        await update.message.reply_text(f"Ошибка при валидации данных: {e}")
изменения по всему файлу, насколько я понимаю, произошли из-за "poetry run pre-commit", так как ранее код всего файла не проходил через этот фильтр.
Изменения коснулись только функции register и web_app_data

2022-10-01 16:09 UTC, NikolaySolop commented on src/bot/services.py
> -    """Проверка пользователя на доступ к регистрации."""
убрал функцию

2022-10-01 16:09 UTC, NikolaySolop commented on src/core/db/db.py
> +        yield session
вернул код как в develop

2022-10-01 16:09 UTC, NikolaySolop commented on src/core/settings.py
> +import os
как я понимаю, это результат проверки pre-commit
из изменений - убрал только переменную DEBUG, которая, как я понимаю, после упрощения кода не нужна

2022-10-01 16:09 UTC, NikolaySolop commented on src/html/registration.html
> +<!DOCTYPE html>
опять же pre-commit
код изменен только в форме
в полях добавлено required, в поле с датой добавлен тип date

2022-10-03 09:15 UTC, NataliyaPavlova commented on src/api/request_models/registration.py
> +class RequestCreate(BaseModel):
давай придерживаться единого стиля в названиях. Вот здесь написано про корректные названия моделей.
https://www.notion.so/codestyle-fc03c29c1edf4df7a335727efb5cc075#0bec639549e0464896c146de3a9c9d3e

2022-10-03 09:15 UTC, NataliyaPavlova commented on src/api/request_models/registration.py
> +    user_id: UUID4
не уверена, что могут быть проблемы, но на всякий случай сделаем одним?  тип у нас UUID (from uuid import UUID)

2022-10-03 09:15 UTC, NataliyaPavlova commented on src/api/request_models/user.py
> +class UserCreate(BaseModel):
название модели - https://www.notion.so/codestyle-fc03c29c1edf4df7a335727efb5cc075#0bec639549e0464896c146de3a9c9d3e

2022-10-03 09:15 UTC, NataliyaPavlova commented on src/core/crud/request.py
> +from sqlalchemy import select, asc
Коля, дира crud со всем содержимым тут не нужна( весь этот функционал должен быть (и есть вроде) в репозитории

2022-10-03 09:15 UTC, NataliyaPavlova commented on src/core/db/repository/user_repository.py
> +        user = await self.session.execute(select(User).where(attr == attr_value))
Антон ответил вот что: надо воссоздавать всю структуру. 
session = get_session()
user_repository = UserRepository(session)
user_service = UserService(user_repository)

если честно, я не успела затестить(  ты попробуешь?

2022-10-03 20:14 UTC, NikolaySolop commented on src/core/db/repository/user_repository.py
> +        user = await self.session.execute(select(User).where(attr == attr_value))
Попробовал по алгоритму выше, но выдает похожую ошибку
 AttributeError: 'async_generator' object has no attribute 'execute' . То есть пытаемся применить метод не к  сессии, а к генератору. У Маруси похожая ошибка

2022-10-04 18:27 UTC, NikolaySolop commented on src/bot/handlers.py
> +            request_repository = RequestRepository(session=session)
Маруся предложила рабочий вариант
Может быть есть лучше?

2022-10-05 09:29 UTC, NataliyaPavlova commented on src/core/services/registration_service.py
> +class RegistrationService:
Николай, а давай все-таки это будет в сервисе для User? Мы не выносим регистрацию в отдельную сущность...

2022-10-05 09:29 UTC, NataliyaPavlova commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
кавычки надо бы одинаковыми везде сделать (двойными)

2022-10-05 09:29 UTC, NataliyaPavlova commented on src/bot/handlers.py
> +        'Это бот Центра "Ломая барьеры", который в игровой форме поможет '
сделай одинаковые кавычки во всех строках, пожалуйста?..

2022-10-05 15:04 UTC, NikolaySolop commented on src/core/services/registration_service.py
> +class RegistrationService:
я правильно понимаю, что достаточно просто переименовать файл src/core/services/registration_service.py на src/core/services/user_service.py?
код оставляю неизменным?

меня просто смутил файл в develop src/core/services/user_task_service.py. Я подумал, что мы все в отдельные сервисы выделяем. Но скорей всего и этот файл ждет слияние с src/core/services/user_service.py, так?

2022-10-05 15:04 UTC, NikolaySolop commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
Тут небольшая дилемма.  poetry-pre commit автоматом изменяет все string/f-string на двойные кавычки. Но в этой строке есть название центра "Ломая барьеры", тогда его придется брать в одинарные кавычки 'Ломая барьеры', а это скорей всего не тот результат, который мы хотим. Оставить так или обернуть название в одинарные кавычки?

2022-10-05 15:04 UTC, NikolaySolop commented on src/bot/handlers.py
> +        'Это бот Центра "Ломая барьеры", который в игровой форме поможет '
Комментарий выше по кавычкам, такой же кейс.

2022-10-05 15:14 UTC, NataliyaPavlova commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
аа, вот они почему тут такие. Может, их заэкранировать с \?

2022-10-05 15:17 UTC, NataliyaPavlova commented on src/core/services/registration_service.py
> +class RegistrationService:
Нене, не переименовать, а перенести твои функции в user_service.py.
У нас есть отдельная сущность UserTask, а есть - User. Для них есть и сервисы, и репозитории, и модели (и таблицы в бд). Для регистрации мы такое не делали - это действие, которое можно сделать с User, а не отдельная сущность.

2022-10-05 15:17 UTC, NataliyaPavlova commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
пропал backslash перед знаком вопроса.)

2022-10-05 16:10 UTC, AntonZelinsky approved these changes

2022-10-05 16:10 UTC, AntonZelinsky commented on src/api/request_models/user.py
> +        if re.compile(VALID_PHONE_NUMBER).search(str(value)) is None:
В другой задаче:
Давайте подключим стороннюю библиотеку для этого, так как пользователь может ввести телефон в десятке разных форматов, ему будет приходить ошибка, а он не будет понимать почему так. Пусть на себя обработку возьмёт либа. 
Лиды, сделайте, пожалуйста, отдельную таску на это.

2022-10-05 16:10 UTC, AntonZelinsky commented on src/api/request_models/registration.py
> +    status: Request.Status = Request.Status.PENDING
Это не должно быть частью модели создания записи, это часть бизнес логики. Если в эту модель передадут статус «заапрувлен», что ты будешь делать?
Я уже писал об этом(

PS, как Наташа писал в другом коменте, у нас нет репозитория регистрация, поэтому, перенеси всё это в пользователя. Если вдруг модель станет очень большой, то разобъётся на несколько таким образом src/api/request_models/user_registration.py и src/api/request_models/user_analitics.py

2022-10-05 16:10 UTC, AntonZelinsky commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
Кавычки экранируй, а в прекомит добавьте правило не исправлять кавычки для ф-строк. 
Добавь информацию в вики, что везде для строк используем теперь двойные кавычки, а так же, сделай пост в общем канале, чтобы все наверняка увидели.

2022-10-05 16:10 UTC, AntonZelinsky commented on src/core/db/repository/request_repository.py
> +    async def get_by_attribute(self, attr_name: str, attr_value: Union[str, bool]) -> Optional[Request]:
Нет, это плохо. Ты используешь потом для получения записей по id, хотя методы `get` и `get_or_none` делают то же самое. Для получения записи по telegram_id сделай метод `get_by_telegram_id` и передавай туда просто id
```
user = await self.user_repository.get_by_attribute("telegram_id", telegram_id)
request = await self.request_repository.get_by_attribute("id", user.id)
```

2022-10-05 16:10 UTC, AntonZelinsky commented on src/core/db/migrations/versions/2022-10-03_18.38.59_shift_update_started_finished.py
> -down_revision = 'd37fa6413c00'
Ой, а это что такое? Так делать нельзя! если будет даунгрэйд миграций, что всё сломается и упадёт! Такой же миграции нет в системе!

2022-10-05 16:10 UTC, AntonZelinsky commented on src/bot/handlers.py
> +            request_repository = RequestRepository(session=session)
[А почему в форе? Забыли как получать значение из генератора? ](https://stackoverflow.com/questions/2419770/how-to-get-one-value-at-a-time-from-a-generator-function-in-python)

Блин, давайте как временный хак сделаем отдельно файл серисы в папке бота, а в нём методы получения сервисов, как раз эти три строки. 
Только пожалуйста, не передавай так аргументы `RequestRepository(session=session)`, так намного проще читается и воспринимается, причём, понимание того что происходит не ухудшилось `RequestRepository(session)`.

2022-10-05 16:10 UTC, AntonZelinsky commented on src/api/request_models/user.py
> +    deleted: bool = False
Зачем это поле передавать при создании? Откуда оно получает значение?

2022-10-05 16:10 UTC, AntonZelinsky commented on src/main.py
> +    await bot_app.updater.start_polling()
Что с поддержкой режима вебхуков произошло? или он в другом файле? 
Тогда этот должен называться типа run_on_pulling

2022-10-05 20:23 UTC, NikolaySolop commented on src/core/db/migrations/versions/2022-10-03_18.38.59_shift_update_started_finished.py
> -down_revision = 'd37fa6413c00'
Вчера при разрешении конфликтов я изучал миграции. У нас 3 миграции в develop
1) [2022-09-20_12.33.13_init.py](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/src/core/db/migrations/versions/2022-09-20_12.33.13_init.py)
```
revision = 'd37fa6413c00'
down_revision = None
```
2) [2022-09-26_00.04.02_edit_usertask_model_photoid.py](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/src/core/db/migrations/versions/2022-09-26_00.04.02_edit_usertask_model_photoid.py)
```
revision = '2c2d12934211'
down_revision = 'd37fa6413c00'
```
3) [2022-10-03_18.38.59_shift_update_started_finished.py](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/src/core/db/migrations/versions/2022-10-03_18.38.59_shift_update_started_finished.py)
```
revision = '0c58d989449f'
down_revision = 'd37fa6413c00'
```
Получается, что 2 и 3 миграция ссылаются на 1ую.  Разве они не должны быть выстроены последовательно? Или я ошибаюсь и там все ок?
Это исправление приводит миграции в последовательность, то есть 3я миграция ссылается на 2ую.

В предыдущем комите специально обращал на это [внимание](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/commit/283807c07a3f8a27301098f426136364223f8bad#commitcomment-85835787)

2022-10-05 20:23 UTC, NikolaySolop commented on src/bot/handlers.py
> +            request_repository = RequestRepository(session=session)
с синхронным генератором так работает, с асинхронным нет. Я обращал внимание на эту проблему ранее в слаке [здесь](https://practicum-students.slack.com/archives/C03SXFKDWJC/p1664864035514679?thread_ts=1664823266.257539&cid=C03SXFKDWJC)

2022-10-05 20:23 UTC, NikolaySolop commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
- Добавил информацию в [вики](https://www.notion.so/codestyle-fc03c29c1edf4df7a335727efb5cc075)
- Объявление в [слаке](https://practicum-students.slack.com/archives/C03SXFKDWJC/p1664997031923599)

2022-10-05 20:29 UTC, NikolaySolop commented on src/bot/handlers.py
> +        registration_service = await get_registration_service_callback(session)
Если я вызываю сессию в функции `async def get_registration_service_callback(sessions)`, а именно так:

```
async def get_registration_service_callback():
session = get_session()
     async for session in sessions:
         request_repository = RequestRepository(session)
         user_repository = UserRepository(session)
         registration_service = RegistrationService(user_repository, request_repository)
         return registration_service
```
то при попытке записи в БД опять выдает ту же ошибку: `AttributeError: 'NoneType' object has no attribute 'twophase'`

2022-10-06 06:56 UTC, NataliyaPavlova commented on src/core/services/user_service.py
> +class RegistrationService:
мы вроде бы договорились, что не будет RegistrationService? и что функции из этого класса надо перенести в класс UserService в файл user_service.py. Мы друг друга не поняли?

2022-10-06 06:56 UTC, NataliyaPavlova commented on src/bot/services.py
> +            f' новости Центра "Ломая барьеры" - вступайте в нашу группу '
кавычки остались одинарными( надо поправить.

2022-10-06 06:56 UTC, NataliyaPavlova commented on src/bot/handlers.py
> +        'Это бот Центра "Ломая барьеры", который в игровой форме поможет '
и здесь кавычки тоже остались прежними(

2022-10-06 17:54 UTC, NataliyaPavlova approved these changes

2022-10-06 19:50 UTC, merged