Настройка Swag
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #211
Opened 2023-02-13 17:35 UTC by Geroy4ik

Задача https://www.notion.so/Deploy-1f2b204a049c4446b0babc2102500094
1. Сделал чтобы запросы к API шли только через префикс api/ , **но отвалились /docs**. Можно пойти другим путем и добавить параметр root_path либо к команде запуска uvicorn(--root_path /api) либо app = FastAPI(root_path="/api")
2. Добавил volume для хранения фотоотчетов, но не очень понятно где они будут храниться на сервере и по какому адресу их доставать, потому что в задаче написано static/user_reports, но в проекте в корне создаются data/user_reports. Или static/user_reports это внешний адрес?
3. Добавил доступ к фотоотчетам только для авторизованных пользователей(администраторам и психологам).

2023-02-13 17:49 UTC, Geroy4ik commented
Я так понимаю сейчас на сервере 2 контейнера с фронтом и бэком никак не связаны?

2023-02-13 19:35 UTC, ADesBiysk reviewed
2. Сейчас фотографии будут храниться просто в volume на сервере. Дальше посмотрим. Все пути нужно привести к одному знаменателю.

2023-02-13 19:35 UTC, ADesBiysk commented on docker-compose.yaml
> +      - user_reports:/LOMAYA_BARYERY_BACKEND/data/user_reports/
Сейчас это директория data, но мне кажется, что они должны быть в директории static. 
А уже в ней в разных директориях будут храниться иллюстрации к заданиям и фотографии из отчётов. 
Иллюстрации заданий тоже надо вынести из директории src, поскольку они могут добавляться или удаляться в будущем.

2023-02-13 19:35 UTC, ADesBiysk commented on docker-compose.yaml
> +  frontend:
У нас есть ещё репозиторий с фронтом https://github.com/Studio-Yandex-Practicum/lomaya_baryery_frontend и нужно чтобы его контейнер тоже пересобирался и запускался на сервере автоматически, когда мержится PR.
У тебя доступ к нему тоже должен  быть.

2023-02-13 19:35 UTC, ADesBiysk commented on nginx/default.conf
> +    location /api/ {
Swagger обязательно нужен. Давай сделаем как предлагаешь, добавим app = FastAPI(root_path="/api")

2023-02-14 11:11 UTC, Geroy4ik commented on docker-compose.yaml
> +      - user_reports:/LOMAYA_BARYERY_BACKEND/data/user_reports/
Получается в корне будет еще одна директория static/ вместо data/. Там будут директории tasks/ и user/reports. А в src останется static/ с формой регистрации. Я правильно понял?

2023-02-14 16:41 UTC, Geroy4ik commented on docker-compose.yaml
> +  frontend:
Я думаю лучше всего добавить сеть между двумя контейнерами.

2023-02-15 05:15 UTC, ADesBiysk commented on docker-compose.yaml
> +      - user_reports:/LOMAYA_BARYERY_BACKEND/data/user_reports/
Да. 
Единственное, форма регистрации сейчас напрямую не будет отдаваться. Она будет предзаполняться и отдаваться через специальный эндпойнт (выполняется в отдельной задаче). Поэтому её не трогаем.

2023-02-15 05:23 UTC, ADesBiysk reviewed
Давай изображения удалим из этого PR. Для них надо будет править описание и изменять некоторые файлы. Сделаем это отдельно. А для того чтобы сейчас работало, можно будет один раз скопировать в нужную директорию на сервере.

2023-02-15 05:26 UTC, ADesBiysk commented on src/api/routers/administrator.py
> +        responses={
Сейчас выполняется по другому, словарь генерируется функцией. Посмотри пример в других эндпойнтах.

2023-02-16 17:24 UTC, AntonZelinsky approved these changes

2023-02-16 17:24 UTC, AntonZelinsky commented on nginx/default.conf
> +    set $frontend "http://frontend";
А почему он может быть поднят не в одной сети? Зачем их разделять? Пусть будет в одной сети.

2023-02-16 17:24 UTC, AntonZelinsky commented on nginx/default.conf
> +    location /api/(docs|redoc|openapi.json) {
У нас есть редок?

2023-02-16 17:24 UTC, AntonZelinsky commented on docker-compose.yaml
>    nginx_config:
nginx должен мапиться в папку, а не в волум, чтобы его можно было легко руками отредактировать и перезапустить сервер.

2023-02-16 17:24 UTC, AntonZelinsky commented on src/api/routers/administrator.py
> +        pass
А вызвать /me вместо этого мы не можем? Ведь суть та же самая.

2023-02-16 17:24 UTC, AntonZelinsky commented on nginx/default.conf
> +    #     proxy_pass              http://backend:8000/administrators/is_authenticated;
Мы это всё можем протестировать сейчас?
Если нет, то предлагаю всё равно мержить сейчас, чтобы выливаться на прод, а потом уже добить эту задачку

2023-02-16 17:29 UTC, ADesBiysk commented on src/application.py
> +    app = FastAPI(debug=settings.DEBUG, root_path="/api")
Картинки надо полностью удалить не из репозитория, а из PR.

2023-02-17 06:42 UTC, Geroy4ik commented on nginx/default.conf
> +    location /api/(docs|redoc|openapi.json) {
Да

2023-02-17 07:32 UTC, Geroy4ik commented on nginx/default.conf
> +    set $frontend "http://frontend";
Если контейнер с бэкендом будет запускаться, но при этом контейнера с фронтом тоже не будет(сломается что-нибудь), то nginx/swag работать откажется пока frontend не появится в общей сети, тогда и бэкенд работать не будет.

2023-02-17 08:48 UTC, Geroy4ik commented on src/api/routers/administrator.py
> +        pass
В принципе можно, просто тогда будет делаться бесполезный запрос в БД. Мне переделать на /me или оставить как есть?

2023-02-17 09:19 UTC, Geroy4ik commented on nginx/default.conf
> +    #     proxy_pass              http://backend:8000/administrators/is_authenticated;
У меня работало с моим тестовым администратором. Без авторизации возвращается статус 401, с валидным токеном открывается нужный файл. Сейчас только надо поменять: swag возвращает 401 с типом html, а не json.

2023-02-17 10:37 UTC, Geroy4ik commented on nginx/default.conf
> +    #     proxy_pass              http://backend:8000/administrators/is_authenticated;
Поменял ответ на json.

2023-02-17 10:38 UTC, Geroy4ik commented on docker-compose.yaml
>    nginx_config:
Это я забыл удалить volume, который нигде не использовался еще до меня.

2023-02-17 23:53 UTC, AntonZelinsky commented on nginx/default.conf
> +    location /api/(docs|redoc|openapi.json) {
А где его можно увидеть? Что-то я искал в файлах и не нашёл. Или это автогенерируемая штука? Можно ссылку на него, интересно посмотреть

2023-02-18 00:16 UTC, AntonZelinsky requested changes

2023-02-18 00:16 UTC, AntonZelinsky commented on docker-compose.yaml
>      volumes:
Чуть выше указан интересный email

2023-02-18 00:16 UTC, AntonZelinsky commented on nginx/default.conf
> +    set $frontend "http://frontend";
Вообще, деплои фронта сделаны не очень хорошо. 
Сейчас в приложении подымается два контейнера ngix, один [для бэка, другой для фронта](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_frontend/blob/develop/Dockerfile). Это полная лажа!
Сам по себе фронт — это набор html, cssl, js файлов, эти файлы статические и не требуют ничего, кроме того, чтобы их отдали в браузер. Соответственно, докер контейнер должен просто выполнять команду сборки и ложить в какую-то часть себя, а главный докер композ файл должен просто поддтягивать их и мапить с каким-то волумом, на который будет смотреть nginx и отдавать их при запросе в корень. 

Всё должно быть сделано так же как было у вас на фудграме.
1. в этом файле нужно обновить докер файл фронта, [пример как сделано у Вани](https://github.com/Ivan-Skvortsov/foodgram-project-react/blob/master/frontend/Dockerfile), у нас почти то же самое, но туда ngixn засунут зачем-то. 
2. Обновить докер-композ файл как [это было в фудграме](https://github.com/Ivan-Skvortsov/foodgram-project-react/blob/master/infra/docker-compose.yml#L9-L12), чтобы файлы мапились в какую-то папку или волум (кажется, что волум правильнее, чтобы не было мусора в системе). Заметьте, что композ файл просто выполнит команду копирования один рас и умрёт до следующего перезапуска докера.
3. Настроить nginx в нашем докер-композ файле [по примеру фодграма))](https://github.com/Ivan-Skvortsov/foodgram-project-react/blob/master/infra/docker-compose.yml#L33), чтобы он смотрел в ту же папку или тот же волум. Это позволит просто смотреть на те статические файл и отдавать nginx их по запросу пользователя.
4. Настроить nginx конфиг [файл по примеру фудграма))))](https://github.com/Ivan-Skvortsov/foodgram-project-react/blob/master/infra/nginx.conf#L30-L42), чтобы отдавалась статика.
5. Обновить деплой фронта. Старт приложения должен просто перезапускать контейнер nginx и всё.

@ADesBiysk вот это на мой взгляд правильный подход к делпою фронта и бэка при разработке!

2023-02-18 12:12 UTC, Geroy4ik commented on nginx/default.conf
> +    location /api/(docs|redoc|openapi.json) {
Fastapi [сам генерирует](https://fastapi.tiangolo.com/features/#automatic-docs) и swagger и redoc. Соответственно их можно увидеть в /docs и /redoc.

2023-02-18 20:31 UTC, ADesBiysk commented on docker-compose.yaml
>      volumes:
Это я регистрировал для личного кабинета Zero SSL. Если не передавать в качестве параметра, то сертификат не сгенерируют.

2023-02-19 16:10 UTC, AntonZelinsky commented on src/api/routers/administrator.py
> +        pass
В целом, можно оставить, это ни на что не влияет, главное, чтобы если токен подставляется какой-то левый он получал ошибку. Можно попросить чтобы токен сгенерили на одном сикрет_кие, а потом на другом попробовать исопльзвоать тот токен, если проверки работают правильно, то должна быть ошибка. Но в целом, не критично, так как тут главное не дать попасть в открытый доступ эти картинки.

2023-02-21 15:07 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +        error 502 = @fallback;
Похоже, тут подразумевалась директива error_page?

2023-02-21 15:10 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +    location /static/user_reports/ {
Думаю, стоит сразу [поправить настройки](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/a61c86f702052d5f0e0d23f1aeb2a015233e3476/src/core/settings.py#L67), т.к. сейчас в базу будет сохраняться другой урл к юзер репортам.

2023-02-21 15:57 UTC, Geroy4ik commented on nginx/default.conf
> +        error 502 = @fallback;
Да, опечатка.

2023-02-23 22:42 UTC, AntonZelinsky approved these changes

2023-02-23 22:42 UTC, AntonZelinsky commented on .gitignore
> +/static/user_reports/
```suggestion
static/
```

2023-02-23 22:42 UTC, AntonZelinsky commented on docker-compose.yaml
> +      - tasks:/LOMAYA_BARYERY_BACKEND/static/tasks/
Данные пользователя Монтируем не в волум, а в папку

2023-02-23 22:42 UTC, AntonZelinsky commented on nginx/default.conf
>      location ~ /\.ht {
Это файлы Apache сервера, не знаю зачем они тут.

2023-02-23 22:42 UTC, AntonZelinsky commented on nginx/default.conf
> +        proxy_pass $frontend;
Так работать не будет?
```suggestion
        proxy_pass http://frontend;
```

2023-02-23 22:42 UTC, AntonZelinsky commented on src/core/settings.py
> +        return BASE_DIR / "static/tasks"
```suggestion
        return BASE_DIR / "static" / "tasks"

```

2023-02-23 22:42 UTC, AntonZelinsky commented on src/core/settings.py
> +        return BASE_DIR / "static/user_reports"
Тут тоже используй pathlib

2023-02-26 17:28 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +    set $frontend "http://frontend";
@Geroy4ik, а почему ты не хочешь сделать, как Антон рекомендует? Мне кажется, так даже будет проще, чем заморачиваться с сетями/разными докер компоуз и проч. Просто, т.к. фронт и бэк - это разные репозитории, то придётся править [репо с фронтом ](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_frontend)в том числе.

На мой взгляд, должно быть так:

В репозитории с **бэкэндом**:
1. В докер-компоуз добавить сервис frontend, который просто будет тянуть [пакет с фронтом](https://github.com/studio-yandex-practicum/lomaya_baryery_frontend/pkgs/container/lomaya_baryery_frontend) и мапить его в волум (например, frontend_volume)
2. Поправить сервис swag, чтобы мапить frontend_volume в папку в контейнере
3. Поправить конфиг nginx, чтобы раздавать статику из этой папки

В репозитории с **фронтом**:
1. Исправить Dockerfile, убрать из него nginx и просто билдить проект
2. Удалить docker-compose
3. Поправить github workflows. Сделать, чтобы при пуше в ветку просто билдился образ и заливался на github packages. А для деплоя сделать чтобы просто пулился этот образ и перезапускался контейнер, используя имеющийся docker-compose бэкенда. Возможно, еще нужно будет nginx перезапустить (который у нас swag). 

P.S.: перечитал свою писанину - по сути я почти слово в слово Антона перепечатал 😄

2023-03-01 10:33 UTC, Geroy4ik commented on nginx/default.conf
> +    set $frontend "http://frontend";
Возникла проблема - если из Dockerfile'а фронта убрать
```Dockerfile
FROM nginx:1.16.0
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
```
То сервис фронта выходит с кодом 0 при запуске. Логов никаких в контейнере нет и я не понимаю в чем причина.

2023-03-01 12:49 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +    set $frontend "http://frontend";
Это ок) Код 0 говорит о том, что приложение успешно выполнило свои задачи и завершилось.

2023-03-02 12:27 UTC, Geroy4ik commented
@ADesBiysk  Насчет фронта - у меня нет прав для пуша в собственную ветку в репозитории фронта.

2023-03-02 13:08 UTC, Ivan-Skvortsov commented on docker-compose.yaml
>    nginx_config:
Волум нигде не используется, нужно его удалить

2023-03-02 13:15 UTC, Ivan-Skvortsov commented on docker-compose.yaml
> +      - frontend_volume:/var/frontend/
Мне кажется, нужно навести порядок со статикой. 
Сейчас у нас получается, что в контейнере swag появятся папки:
`/var/static`
`/var/html/static`
При этом в папке `/var/static` будет лежать пустая папка tasks, а все таски будут находиться в  `/var/html/static/tasks/`

Предлагаю все сложить в одно место:
/var/html/frontend - волум фронта
/var/html/static - волум с тасками и шаблонами
/var/html/user_reports - папка из гостевой ОС с репортами

Ну либо как-то по-другому)

2023-03-02 13:15 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +        error_page 401 = @unauthorized;
```suggestion
        error_page 401 403 = @unauthorized;

```

2023-03-02 13:16 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +    #    auth_request_set $auth_status $upstream_status;
Раскомментируй, пожалуйста код

2023-03-02 13:20 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +    #     proxy_pass              http://backend:8000/administrators/is_authenticated;
В том виде, в котором сейчас реализован эндпойнт `is_authenticated` нас пустит даже без токена) Достаточно будет передать в хедере параметр `Authorization` с содержимым `Bearer любой_рандомный_набор_символов`
Предлагаю все же использовать здесь `/me`.

И тут тоже раскомментируй все плиз)

2023-03-02 13:20 UTC, Ivan-Skvortsov commented on nginx/default.conf
>      location ~ /\.ht {
Ненужные директивы лучше удалить

2023-03-02 13:24 UTC, Ivan-Skvortsov commented on nginx/default.conf
Я бы еще добавил сюда заголовки безопасности. 
Например, как в [фудграме ](https://github.com/Ivan-Skvortsov/foodgram-project-react/blob/640c2d3137e3b4e1df55d1b7b7ffa458b47c9a30/infra/nginx.conf#L6-L10).
Либо [вот тут](https://itsecforu.ru/2022/06/16/%F0%9F%8C%90-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%BE%D0%B2-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82/) можно почитать

2023-03-02 13:28 UTC, Ivan-Skvortsov commented
> @ADesBiysk Насчет фронта - у меня нет прав для пуша в собственную ветку в репозитории фронта.

Я на фронте [сделал ПР](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_frontend/pull/25), с этими конфигами бэка будет работать. Как закончим тут - зальем там)

Только нужно будет в воркфлоу поменять [путь деплоя](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/3d6958c89b2cbba0ba629777001d91c2258c3e78/.github/workflows/deploy_stage.yaml#L13-L14), чтобы было одинаково на [фронте](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_frontend/blob/102b5f4561da8e2af9320b388318c312006e5893/.github/workflows/deploy_stage.yaml#L13-L14) и бэке

2023-03-02 15:19 UTC, Ivan-Skvortsov commented on docker-compose.yaml
> +      - frontend_volume:/var/frontend/
> При этом в папке `/var/static` будет лежать пустая папка tasks, а все таски будут находиться в `/var/html/static/tasks/`

Окей, это я немного намудрил с волумами у себя)
Но тем не менее, думаю, стоит навести порядок со статикой

2023-03-04 08:02 UTC, Ivan-Skvortsov commented on nginx/default.conf
>      # deny access to .htaccess/.htpasswd files
Удали эти директивы плиз

2023-03-04 08:07 UTC, Ivan-Skvortsov commented on nginx/default.conf
> +    add_header  X-Frame-Options "SAMEORIGIN" always;
Давай заголовки перенесём в блок https

2023-03-04 08:07 UTC, Ivan-Skvortsov approved these changes
Перед деплоем нужно поправить [пути в воркфлоу](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/905b831970cb5e46fc7a086bee69b19a0701435e/.github/workflows/deploy_stage.yaml#L13-L14).
Плюс, т.к. в настройках поменялся путь к статике, нужно не забыть переложить задания из `/src/static/tasks` в `/static/tasks`, иначе опять сломается рассылка.
Ну, либо вернуть в настройках старый путь)

2023-03-04 08:21 UTC, ADesBiysk commented
> Перед деплоем нужно поправить [пути в воркфлоу](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/905b831970cb5e46fc7a086bee69b19a0701435e/.github/workflows/deploy_stage.yaml#L13-L14). Плюс, т.к. в настройках поменялся путь к статике, нужно не забыть переложить задания из `/src/static/tasks` в `/static/tasks`, иначе опять сломается рассылка. Ну, либо вернуть в настройках старый путь)

Давай перенос файлов сделаем в соседней ветке. Там и URL нужно ещё поменять в базе за одно. Я напишу, что нужно сделать.

2023-03-04 11:40 UTC, Geroy4ik commented
Перенес картинки для заданий из src/static/tasks в static/tasks. Добавил настройку ROOT_PATH, т.к. ничего работать не будет без прокси сервера(при локальном запуске).

2023-03-04 18:31 UTC, Ivan-Skvortsov commented
> Добавил настройку ROOT_PATH, т.к. ничего работать не будет без прокси сервера(при локальном запуске).

Тогда нужно в окружения в воркфлоу добавить эту переменную. И, по хорошему, в конфиге nginx тоже её использовать. Иначе при запуске на сервере работать не будет)

2023-03-04 18:32 UTC, merged