get_task_by_user method, send_task_callback for bot
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #60
Opened 2022-10-18 10:05 UTC by Dinara-F

Я не знаю, почему подсвечивается код, который я спуллила. В user_task_repository мой код в строчках 71-81. В user_task_service 43-44.

2022-10-18 15:36 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +    async def get_task_by_user(self, user: User, day_number: int, shift_id: int) -> dict:
Функции не должны возвращать словари без чёткого обоснования именно такого формата. Словарь может иметь произвольную структуру, т.е. для его использования нужно посмотреть код функции, его формирующей.
Опишите специальные DTO модели pydantic и возвращайте их.

2022-10-18 15:36 UTC, ADesBiysk commented on src/core/services/user_task_service.py
> +    async def get_task_by_user(self, user_id: UUID, day_number: int, shift_id: int) -> dict:
Такое же замечание.

2022-10-21 18:38 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +        task_id_url = dict(*task_id_url)
Функция возвращает словарь, а не ShortTaskResponse.

2022-10-21 18:38 UTC, ADesBiysk commented on src/api/response_models/task.py
> +    task_description: Optional[str]
Поле description в Task не может быть пустым. Зачем это изменение?

2022-10-22 10:21 UTC, Wiped-Out requested changes

2022-10-22 10:21 UTC, Wiped-Out commented on src/core/services/user_task_service.py
> +        return await self.user_task_repository.get_task_by_user(user_id, day_number, shift_id)
В функцию get_task_by_user передается первым аргументом переменная user_id с типом UUID, но при этом первый параметр в функции user_task_repository.get_task_by_user - это user с типом models.User. Это ошибка или где-то во внутренних процессах класса мы получаем models.User по user_id?

2022-10-22 10:21 UTC, Wiped-Out commented on src/bot/services.py
> +async def send_task_callback(user: models.User, description: str, task_url: str):
Из переменной user в функции используется только telegram_id. Может быть в функцию передавать только telegram_id?

2022-10-24 19:25 UTC, NataliyaPavlova commented on src/bot/services.py
я не поняла - какие изменения у тебя в этом файле? если только порядок строк, то удали плиз файл из ПР

2022-10-24 19:25 UTC, NataliyaPavlova commented on src/bot/jobs.py
> +        chat_id='5702444617',  # заменить на user.telegram_id
это твой хардкод?

2022-10-24 19:25 UTC, NataliyaPavlova commented on src/bot/jobs.py
> +async def send_task_job(context: CallbackContext, telegram_id: int, description: str, task_url: str):
добавь, пожалуйста, сюда еще тип возвращаемого значения.

2022-10-24 20:42 UTC, Dinara-F commented on src/bot/services.py
после демо я перенесла метод отправки сообщения отсюда в jobs.py

2022-10-24 20:42 UTC, Dinara-F commented on src/bot/jobs.py
> +        chat_id='5702444617',  # заменить на user.telegram_id
нет, мой код send_task_job

2022-10-25 00:16 UTC, AntonZelinsky commented on src/core/services/user_task_service.py
> +        return await self.__user_task_repository.get_task_by_user(user_id)
Где ссылка на тикет? как понять какую задачу ты решаешь? 
Перед запросом данных из базы, нужно провалидировать, что вообще есть такой пользователь.

То есть, из юзер репозитория достать юзера, в данном случае

2022-10-25 00:16 UTC, AntonZelinsky commented on src/core/db/repository/user_task_repository.py
> +            .where(UserTask.user_id == user_id, UserTask.task_date == task_date)
Суда по запросу, ты пытаешь получить задание на сегодня, а название говорит совсем другое. 
Тогда, ещё нжуно проверить, что пользователь в смене и она запущена! Но это в уровне сервиса

2022-10-25 00:16 UTC, AntonZelinsky commented on src/bot/jobs.py
> +        ),
Почему два разных сообщения и почему просто ссылку отправляешь на картинку? Что за ерунда?

И не понятно кто вызывает эту функцию, найти в твоём коде и в репозитории я не смог!(

2022-10-25 09:09 UTC, Dinara-F commented on src/bot/jobs.py
> +        ),
В вики про отправку задания написано: "При этом обязательно не только словесное формулирование задания, но и наличие наглядной карточки (сперва карточка, затем текст)". Я не придумала другого способа отправить картину. Я разберусь.
Моей задачей было только написать этот job

2022-10-28 05:38 UTC, ADesBiysk commented on src/bot/services.py
Этот файл надо удалить из PR. Здесь нет изменений.

2022-10-28 05:38 UTC, ADesBiysk commented on src/core/services/user_task_service.py
> +    async def get_today_task_by_user(self, user_id: UUID) -> ShortTaskResponse:
Где вызывается данный метод и кто будет обрабатывать исключения?

2022-10-28 05:38 UTC, ADesBiysk commented on src/bot/jobs.py
> +async def send_task_job(context: CallbackContext, telegram_id: int, description: str, task_url: str) -> None:
Где будет вызываться данная функция, причём со всем контекстом? Предполагаю, что нужна функция, которая будет вызываться по расписанию. Она будет брать участников текущей активной смены и рассылать им задание, возможно, используя данную функцию.

2022-10-31 17:23 UTC, AntonZelinsky approved these changes

2022-10-31 17:23 UTC, AntonZelinsky commented on src/bot/jobs.py
> +        task_info = await user_task_service().get_today_task_by_user(user.id)
Эти три строки — это часть бизнес логики. Тебе нужно вызывать один сервис, который будет возвращать список объектов, который содержит всю необходимую информацию. Внутри сервиса могут быть обращения к другим репозиториям для получения всех необходимых знаний.
И по списку из сервиса ты проходишься циклом и только отправляешь значения.
И хорошо бы решать задачу в 1 - 2 запроса, а не в `N * 2 + 1`, где N — это количество учеников. 
Сейчас, когда будешь переделывать всё на один сервис, эта проблема у тебя не возникнет, но вообще, если ты получаешь какие-то данные из нашей базы, то их как правило не нужно валидировать. (например, проверять есть ли такой пользователь, если в базе есть такое значение, значит и пользователь такой есть)


Как итог, я предлагаю обращаться к сервису смены и у него просить получить все задания к отправке (и получать всю необходимую информацию). 
Почему именно сервис смены? Потому что это всё относится именно к смене, это её зона ответственности, определить кто сейчас в активной смене и какие у них задания. Тут смена главная сущность!

2022-10-31 17:23 UTC, AntonZelinsky commented on src/bot/main.py
> +        send_task_job, time(hour=settings.SEND_NEW_TASK_HOUR, tzinfo=pytz.timezone("Europe/Moscow"))
send_daily_tasks_job

2022-10-31 17:23 UTC, AntonZelinsky commented on src/bot/main.py
>          send_no_report_reminder_job,
send_deily_tasks_remainder_job

2022-10-31 17:23 UTC, AntonZelinsky commented on src/bot/main.py
> +        send_task_job, time(hour=settings.SEND_NEW_TASK_HOUR, tzinfo=pytz.timezone("Europe/Moscow"))
И сетингам хорошо бы тоже дать более подходящие имена

2022-11-01 18:44 UTC, Dinara-F commented
Активные участники определяются не сменой, а статусом реквеста (в пр 5 пропусков меняется он, если участник вылетает), поэтому я их фильтрую через него

2022-11-03 14:50 UTC, Dinara-F commented
@AntonZelinsky @ADesBiysk @NataliyaPavlova пожалуйста, посмотрите)

2022-11-04 11:46 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +            task_info = await self.__session.execute(
Также осталось много запросов. Попробуй забрать их за один запрос.

2022-11-04 11:46 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +                task_id=task_info["task_id"],
Надо использовать промежуточную DTO модель для возврата данных из репозиториев. 
И для создания класса попробуй просто передавать значения в конструктор через распаковку **. Такой вариант надо исправлять при изменении модели, что очень неудобно.

2022-11-05 19:58 UTC, AntonZelinsky approved these changes
Поправь эти коменты и можешь мержить.

2022-11-05 19:58 UTC, AntonZelinsky commented on src/core/db/repository/shift_repository.py
> +            .where(Request.status == Request.Status.APPROVED.value, UserTask.task_date == task_date)
В поменяй условия местами, быстрее работать будет.

2022-11-05 19:58 UTC, AntonZelinsky commented on src/core/services/user_service.py
> +        return await self.user_repository.get_users_in_active_shift()
Репозитории должны быть приватными в сервисах, сессии приватными в репозиториях, а сервисы приватные во вьюшках и методах бота.

2022-11-05 19:58 UTC, AntonZelinsky commented on src/core/services/user_task_service.py
> +        return await self.__user_task_repository.get_tasks_by_usertask_ids(usertask_ids)
Вообще, это нужно было в один метод репозитория объеденить. Но ладно, пусть сейчас остаётся два, а потом вернёмся и отрефакторим.

2022-11-05 19:58 UTC, AntonZelinsky commented on src/core/db/repository/user_repository.py
> +            select(User).where(Shift.status == Shift.Status.STARTED.value).join(User.shifts)
Раздели на 3 строки, чтобы улучшить читаемость.

2022-11-06 15:08 UTC, merged