Feature/spisok zadach po status i shift
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #70
Opened 2022-10-29 22:11 UTC by valnem12

The task draft version has been completed. 
Both Get and Patch seemed to work.

The output supports list of dict and single dict per one shift only.

Can't achieve the follow requirement:

**_" Список формируется по убыванию поля started_at. "_**

Within the code:
 ```
@router.get(
        "/{shift_id}/{status}",
        response_model=list[UserTaskStatusByShiftResponse],
        summary="Получения списка задач на проверку по полям status и shift_id.",
    )
    async def get_tasks_by_status(
        *,
        self,
        shift_id: **list[UUID]** = Path(..., title="ID смены"),
        status: UserTask.Status,
    ) -> list[dict]:
```
the output is the assertion error:
```
assert is_scalar_field(
                   AssertionError: Path params must be of one of the supported types
```

2022-11-03 17:36 UTC, ADesBiysk reviewed
Ошибки для всех методов одинаковые.

2022-11-03 17:36 UTC, ADesBiysk commented on src/api/request_models/user_task.py
> +class ChangeStatusByShift(RequestBase):
Имя модели не соответствует правилам: https://www.notion.so/codestyle-fc03c29c1edf4df7a335727efb5cc075

2022-11-03 17:36 UTC, ADesBiysk commented on src/core/db/models.py
> +    # CheckConstraint,
Нужно всегда убирать закомментированный код.

2022-11-03 17:36 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +        print(result)
Print надо убрать.

2022-11-03 17:36 UTC, ADesBiysk commented on src/api/routers/user_tasks.py
> +    ) -> list[dict]:
Почему словарь? Должна быть response модель.

2022-11-03 17:36 UTC, ADesBiysk commented on src/api/routers/user_tasks.py
> +        shift_id: UUID = Path(..., title="ID смены"),
Зачем здесь ellipsis?

2022-11-03 17:36 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +        keys = ['shift_id', 'shift_status', 'shift_started_at', 'user_task_id',
Не надо так. Создайте DTO модель в виде dataclass и возвращайте его.

2022-11-03 17:36 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +            raise HTTPException(status_code=404, detail="Hero not found")
Пусть будет просто ValueError.

2022-11-05 02:18 UTC, valnem12 commented on src/core/db/repository/user_task_repository.py
> +            raise HTTPException(status_code=404, detail="Hero not found")
done

2022-11-05 02:18 UTC, valnem12 commented on src/core/db/repository/user_task_repository.py
> +        print(result)
done

2022-11-05 02:18 UTC, valnem12 commented on src/core/db/repository/user_task_repository.py
> +        keys = ['shift_id', 'shift_status', 'shift_started_at', 'user_task_id',
done

2022-11-05 08:46 UTC, ADesBiysk reviewed
Приведите в порядок PR. В него попало очень много лишних файлов.

2022-11-05 15:58 UTC, ADesBiysk reviewed
Не нужно решать проблемы с flake8 за всех. Удали все лишние файлы из PR, т.е. те которые не относятся к решению твоей задачи.

2022-11-05 21:35 UTC, AntonZelinsky requested changes

2022-11-05 21:35 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +    def validate_finished_at_later_than_4_month(cls, value: datetime) -> datetime:  # noqa
На что линтер жалуется? Почему его пришлось отключать?

2022-11-05 21:35 UTC, AntonZelinsky commented on src/api/request_models/shift.py
> +    def validate_finished_at_later_than_4_month(cls, value: datetime) -> datetime:  # noqa
Тебе это точно нужно делать? Очень много файлов затрагивает и у других будут конфликты, хотя твой код должен проходить и без этого

2022-11-05 21:35 UTC, AntonZelinsky commented on src/api/routers/user_tasks.py
> +<<<<<<< feature/spisok_zadach_po_status_i_shift_id
Конфликт криво разрешён. Нужно исправить.

2022-11-05 21:35 UTC, AntonZelinsky commented on src/core/db/repository/shift_repository.py
> +        return shift                   # noqa
Зачем?

2022-11-05 21:35 UTC, AntonZelinsky commented on src/core/db/repository/user_task_repository.py
> +from datetime import date
Исправь проблему с окончанием строк в коде, твои комиты не должны перехерячивать весь код, так как его ревьювить невозможно.

2022-11-05 21:36 UTC, valnem12 commented on src/api/request_models/shift.py
> +    def validate_finished_at_later_than_4_month(cls, value: datetime) -> datetime:  # noqa
Это не мой код и я не знаю почему он жалуется, это в origin

2022-11-05 21:37 UTC, valnem12 commented on src/core/db/repository/shift_repository.py
> +        return shift                   # noqa
тоже flake8

2022-11-05 21:38 UTC, valnem12 commented on src/core/db/repository/user_task_repository.py
> +from datetime import date
не понял о чем речь

2022-11-05 21:58 UTC, valnem12 commented
> 

как это сделать, не пулить девелоп? аплоадить только свои файлы?

2022-11-05 23:52 UTC, valnem12 commented
Suggested edit:
```diff
diff --git a/src/core/services/user_service.py  b/src/core/services/user_service.py 
new file mode 100644
index 0000000..0f1d5f7
--- /dev/null
+++ b/src/core/services/user_service.py 	
@@ -0,0 +1,51 @@
+from datetime import date, datetime
+
+from fastapi import Depends
+
+from src.api.request_models.user import RequestCreateRequest, UserCreateRequest
+from src.core.db.models import Request, User
+from src.core.db.repository.request_repository import RequestRepository
+from src.core.db.repository.user_repository import UserRepository
+from src.core.settings import settings
+
+
+def validate_date_of_birth(value: date) -> None:
+    """Валидация даты рождения пользователя."""
+    current_year = datetime.now().date().year
+    if current_year - value.year < settings.MIN_AGE:
+        raise ValueError(f'Возраст не может быть менее {settings.MIN_AGE} лет.')
+
+
+async def validate_user_not_exists(
+    user_repository: UserRepository, telegram_id: int = None, phone_number: str = None
+) -> None:
+    """Проверка, что в БД нет пользователя с указанным telegram_id или phone_number."""
+    user_exists = await user_repository.check_user_existence(telegram_id, phone_number)
+    if user_exists:
+        raise ValueError('Пользователь уже зарегистрирован.')
+
+
+async def validate_user_create(user: UserCreateRequest, user_repository: UserRepository) -> None:
+    """Валидация персональных данных пользователя."""
+    validate_date_of_birth(user.date_of_birth)
+    await validate_user_not_exists(user_repository, user.telegram_id, user.phone_number)
+
+
+class UserService:
+    def __init__(
+        self, user_repository: UserRepository = Depends(), request_repository: RequestRepository = Depends()
+    ) -> None:
+        self.user_repository = user_repository
+        self.request_repository = request_repository
+
+    async def user_registration(self, user_data: dict):
+        """Регистрация пользователя. Отправка запроса на участие в смене."""
+        user_scheme = UserCreateRequest(**user_data)
+        await validate_user_create(user_scheme, self.user_repository)
+        user = User(**user_scheme.dict())
+        await self.user_repository.create(user)
+        request = await self.request_repository.get_or_none(user.id)
+        if not request:
+            request_scheme = RequestCreateRequest(user_id=user.id, status=Request.Status.PENDING)
+            request = Request(**request_scheme.dict())
+            await self.user_repository.create(request)
\ No newline at end of file

```

2022-11-06 09:22 UTC, ADesBiysk commented on src/core/db/repository/user_task_repository.py
> +from datetime import date
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings

2022-11-06 17:31 UTC, valnem12 commented on src/core/db/repository/user_task_repository.py
> +from datetime import date
вроде получилось, но по видимому проблема не у меня, а в origin, в сравнение между коммитами все хорошо

2022-11-06 18:17 UTC, AntonZelinsky commented
Предлагаю, создать новую ветку от девелоп и перенести туда свой код, так как тут слишком много конфликтов и вряд ли их удастся вообще разрешить

2022-11-06 19:34 UTC, valnem12 commented
Per peers review will close this PR and reopen a new one.

2022-11-06 19:34 UTC, closed without merging