FIX/repository_refactoring
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #74
Opened 2022-11-03 14:47 UTC by Dinara-F

Задание: вынести дублирующийся методы из конкретных репозиториев в абстрактные.

2022-11-03 17:28 UTC, ADesBiysk reviewed
Замечания для всех файлов одинаковые. Сделай изменения для всех.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/abstract_repository.py
> +        self.model = model
При таком инициализаторе нужно всегда передавать модель БД при создании, что неудобно и может приводить к ошибкам. 
Сделай следующие шаги:
1. Убери model из инициализатора.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/abstract_repository.py
2. Здесь надо сделать так. model = None
Подразумевается, что в классах, наследуемых от этого, эта переменная будет определена.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/photo_repository.py
> +    pass
Посмотри по коду, и если этот репозиторий не используется, давай уберём этот файл. Сомневаюсь, что он понадобится. А если и понадобится, то разработчик сам его добавит.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/abstract_repository.py
> +            raise HTTPException(status_code=HTTPStatus.NOT_FOUND)
Репозиторий не должен использовать исключения http. Лучше такое ValueError. Потом будем использовать кастомные.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/request_repository.py
3. Здесь будет:
model = Request
Аналогично во всех остальных репозиториях.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/request_repository.py
>      async def get_shift_user_ids(self, shift_id: UUID, status: str = Request.Status.APPROVED.value) -> list[UUID]:
Убери значение status по-умолчанию. Это уже относится к бизнес-логике. Если не передаётся конкретный статус, то возвращаем все смены.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/request_repository.py
> +request_repository = RequestRepository(Request)
4. Это уже не нужно. Убираем.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/db/repository/task_repository.py
> +from uuid import UUID
К тебе будет небольшая просьба. Вероятнее всего из-за этой проблемы (https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings) git считает, что файл полностью изменился, что очень неудобно.
Попробуй применить эту настройку и залить файл еще раз. Поможет это или нет. И напиши какую систему используешь: mac, win, linux.

2022-11-03 17:28 UTC, ADesBiysk commented on src/core/services/request_sevice.py
> +    def __init__(self, request_repository: RequestRepository = request_repository) -> None:
Нужно вернуть depends. Должно заработать.

2022-11-05 21:40 UTC, AntonZelinsky commented on src/core/db/repository/abstract_repository.py
Только переменная должна быть protected, чтобы из вне её нельзя было переименовать, но в наследнтках она была доступна.

2022-11-05 21:57 UTC, AntonZelinsky requested changes

2022-11-05 21:57 UTC, AntonZelinsky commented on src/core/db/repository/request_repository.py
> +        request = await self.__session.execute(
А это точно отрабатывает? 😳 Сессия же приватная и она не должна быть видна в наследнтках абстрактного класса.
По идее, она должна быть протектед.

2022-11-05 21:57 UTC, AntonZelinsky commented on src/core/db/repository/shift_repository.py
> +shift_repository = ShiftRepository(Shift)
А зачем это добавлять? Раньше же не нужно было? Стало выглядеть хуже чем было. Предлагаю вернуть как было.

2022-11-05 21:57 UTC, AntonZelinsky commented on src/core/services/request_sevice.py
> +    def __init__(self, request_repository: RequestRepository = request_repository) -> None:
Подозреваю, что пришлось создавать экземпляры репозиториев и импортировать их сюда потому, что в абстрактный класс добавили конструктор, а в его наследники ках этот конструктор не вызывается. Работать не должно. В абстрактном классе не должно быть depends. Он должен вызываться в наследнтках и передаваться в родительский.
У кого тут хромают знания я по ООП?

2022-11-05 21:57 UTC, AntonZelinsky commented on src/core/db/repository/task_repository.py
> +from uuid import UUID
Пока это не будут пофикшены окончание строк, нет смысла смотреть файлы перекоряченные.

Правда, если файлы из неправильных поменялись в правильные, то тогда уже ничего не сделаешь..

2022-11-06 17:07 UTC, ADesBiysk reviewed
Проверяй код на работоспособность перед отправкой. 
Исправь __session на _session.
Отпишись по моей просьбе с настройкой git: какая ОС, пробовала настраивать, что-то изменилось?

2022-11-06 17:07 UTC, ADesBiysk commented on src/core/db/repository/abstract_repository.py
> +        self.__session = session
Сессия должна быть protected, т.е. self._session = session
Проверяла работоспособность? При использовании возникает логичная ошибка: AttributeError: 'ShiftRepository' object has no attribute '_ShiftRepository__session'

2022-11-06 21:57 UTC, Dinara-F commented
@ADesBiysk у меня mac, применила команду git config --global core.autocrlf input

2022-11-09 10:50 UTC, ADesBiysk reviewed
Надо разрешить конфликты и убрать лишние файлы.

2022-11-09 10:50 UTC, ADesBiysk commented on src/core/services/healthcheck_service.py
> +import logging
В этом файле есть изменения? Если нет, то надо убрать.

2022-11-09 10:50 UTC, ADesBiysk commented on src/core/services/task_service.py
> +from src.core.db.repository.task_repository import TaskRepository
Здесь тоже изменилось только оформление. Надо убрать.

2022-11-09 10:50 UTC, ADesBiysk commented on src/core/services/user_service.py
> +        user_repository: UserRepository = Depends(),
Аналогично.

2022-11-09 10:50 UTC, ADesBiysk commented on src/core/services/user_task_service.py
> +from src.core.db.repository.shift_repository import ShiftRepository
Аналогично.

2022-11-09 11:42 UTC, Dinara-F commented on src/core/services/task_service.py
> +from src.core.db.repository.task_repository import TaskRepository
не получилось убрать файл, он автоматически правился при коммите

2022-11-11 15:54 UTC, AntonZelinsky approved these changes

2022-11-11 15:54 UTC, AntonZelinsky commented on src/core/db/repository/abstract_repository.py
> +    _model = None
Давайте всё же инициализировать модель через конструктор, так как пользователь класса может не указать или случайно удалить, модель и всё сломается. А если через инициализатор будет задаваться, то не получится забыть об этом)

2022-11-11 15:54 UTC, AntonZelinsky commented on src/core/db/repository/photo_repository.py
>  class PhotoRepository(AbstractRepository):
Этот репозитоирй точно используется?

2022-11-14 20:50 UTC, Dinara-F commented
@ADesBiysk я добавила модели в дефолтные значения, нужно так или через depends?

2022-11-15 02:07 UTC, ADesBiysk reviewed
Во время инициализации нужен объект модели. Если вызвать Depends, то вернётся экземпляр объекта, что не нужно. Лучше оставить как есть сейчас.
Единственное, я бы использовал инициализатор родительского класса, передавая ему значения.
Проверь, что всё корректно работает. У меня, при попытке посмотреть схему выдаётся такая ошибка:
  File "pydantic/schema.py", line 247, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 215, in pydantic.schema.get_field_info_schema
  File "pydantic/schema.py", line 985, in pydantic.schema.encode_default
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'DeclarativeMeta' is not JSON serializable

2022-11-16 19:05 UTC, Dinara-F commented
@ADesBiysk  я исправила ошибку, унаследовала инит абстракт репозитори, единственное, чтобы все заработало пришлось чуть подправить чужой код в сервисах, где используется бот

2022-11-16 19:25 UTC, ADesBiysk reviewed
Нашел причину. Возможно это какое-то ограничение FastAPI, но в инициализаторе репозитория нельзя использовать модели SQLAlchemy, а только pydantic. Предполагаю, что это связано с depends. Как исправить не смог найти. 

Попробуй просто присваивать модель в инициализаторе, не передавая её в качестве параметра.

2022-11-17 06:39 UTC, ADesBiysk approved these changes
Исправь 2 замечания и можно мержить.

2022-11-17 06:39 UTC, ADesBiysk commented on src/core/db/repository/abstract_repository.py
>      @abc.abstractmethod
__init__ обычно не делают абстрактным.

2022-11-17 06:39 UTC, ADesBiysk commented on src/core/db/repository/photo_repository.py
> +        AbstractRepository.__init__(self, session, model=Photo)
Правильнее так: super().__init__(....

2022-11-17 11:31 UTC, merged