created VerificationNotification class
Studio-Yandex-Practicum/lomaya_baryery_backend pull request #9
Opened 2022-09-17 14:48 UTC by Ponimon4ik

2022-09-18 10:24 UTC, NataliyaPavlova commented on src/bot/services.py
> +
спрячь, пожалуйста, эти константы в тело функций. Мы потом создадим отдельную задачу, где вынесем их все в отдельный файл или таблицу.

2022-09-18 10:24 UTC, NataliyaPavlova commented on src/bot/services.py
> +            )
мне не очень нравится идея с передачей имени и фамилии участника в эту функцию, а потом и в текст. Кажется, что тут много может сломаться. 
давай лучше передавать id участника, а потом вытаскивать user.name, user.surname из базы. И в текст уже вставлять непосредственно имя и фамилию.

2022-09-18 10:24 UTC, NataliyaPavlova commented on src/bot/services.py
> +    async def send_approval_callback(self, id, first_name, second_name):
по имени переменной id непонятно, id чего. Поменяй на более говорящее название?

2022-09-18 10:24 UTC, NataliyaPavlova commented on src/bot/services.py
> +
напиши еще докстринг, что класс делает?

2022-09-18 10:26 UTC, NataliyaPavlova commented on src/bot/services.py
> +            )
и еще у нас везде не first_name, second_name, а name, surname - давай придерживаться единой терминологии, чтобы потом не запутаться. А то придет какой-нибудь Эрих Мария Ремарк, будем думать, как его в бд записать)

2022-09-18 10:36 UTC, petrovskydv requested changes

2022-09-18 10:36 UTC, petrovskydv commented on src/bot/services.py
> +    'проекте. Вы можете написать на почту info@stereotipov.net. Чтобы не '
email надо вынести в настройки, они могут поменять адрес  и лезть из-за этого менять код совсем не хорошо

2022-09-18 10:36 UTC, petrovskydv commented on src/bot/services.py
> +    'в нашу группу https://vk.com/socialrb02'
ссылку на группу тоже в настройки

2022-09-18 10:36 UTC, petrovskydv commented on src/bot/services.py
> +    async def send_approval_callback(self, id, first_name, second_name):
к тому же это [имя встроенной функции](https://docs.python.org/3/library/functions.html), не стоит использовать встроенные имена.

2022-09-18 13:33 UTC, Ponimon4ik commented on src/bot/services.py
> +
Я не против, но хотел уточнить. Разве не проще будет собирать уже готовые константы из модуля, а не выискивать их по функциям? Или все же проще, когда они будут находиться в теле методов, в чем секрет?  Подскажи пожалуйста)

2022-09-18 13:39 UTC, Ponimon4ik commented on src/bot/services.py
> +            )
Может лучше тогда давай передавать объект User ? Уточни пожалуйста. 
С именами параметров согласен, не доглядел)

2022-09-18 13:43 UTC, Ponimon4ik commented on src/bot/services.py
> +            )
Может тогда лучше передавать объект User? Уточни пожалуйста.
С именами параметров согласен, не доглядел

2022-09-18 15:00 UTC, AntonZelinsky submitted a review, later dismissed

2022-09-18 15:00 UTC, AntonZelinsky commented on src/bot/services.py
> +
В этом файле будет ±30 функций (очень гипербализировал, если столько будет, то разнесём по нескольким фалам, но для ясности подойдёт). И у каждой функции будет стоя такая константа и когда ты захочешь узнать что это за константа у функции используется, придётся листать длинющий файл в вверх и выикивать её там среди списка очень похожих констант. 
Пока у нас нет механизма для работы с константами, это только усложняет, плюс, под константу в файле выделяется память, которая будет занята всё время работы приложения, а по сути, эта строка нигде не переиспользуется и вообще не имеет смысла её выносить. Так, приложение будет есть меньше памяти и сразу будет понятно где используется эта строка.

2022-09-18 15:00 UTC, AntonZelinsky commented on src/bot/services.py
> +            )
Ой, Наташа, я тут с тобой немного не согласен, эта функция, по сути, просто рендерит и отправляет сообщение, то есть, по сути, это уровень представления в n-урвоневой моделе архитектуры, пусть функция и находится в сервисе (хорошо бы подумать куда её перенести, если нужно это делать). Задача этой функции, просто отформатировать и вернуть ответ клиенту. 
К тому же, функция вызывшая эту функцию, явно уже будет именть объект User, ведь там будет меняться статус. Я даже соглашусть с Богданом, что можно передать сам объект в эту функцию. Я обдумывал этот вариант, когда описывал задачу, но отмёл из-за того, что хотелось бы иметь ±похожее представление у всех функций, а в другой функцие нужно только id и передавать весь объект, это слишком.

Как итог, разницы нет между этими двумя подходами, это на вкус и цвет, давайте будем передавать сюда весь объект и из него брать все значения.

2022-09-18 15:00 UTC, AntonZelinsky commented on src/bot/services.py
> +    f'проекте. Вы можете написать на почту {ORGANIZATIONS_EMAIL}. Чтобы не '
конфиги так не очень красиво импортить, лучше ипортировать settings, а потом использовать везде `settings.ORGANIZATIONS_EMAIL`, так, сразу будет понятно что за значения и откуда взялось и не нужно листать в начало файла и выискивать где объявлено оно было.

2022-09-18 15:00 UTC, AntonZelinsky commented on src/core/settings.py
> +ORGANIZATIONS_GROUP = 'https://vk.com/socialrb02'
:+1: Согласен, что не нужно выносить в .env, эта штука меняться не будет.

2022-09-18 15:00 UTC, AntonZelinsky commented on src/bot/services.py
> +class VerificationNotification:
Ваши тимлиды предложили не использовать этот класс и я на все 100 согласен, переделай на обычные функции, потом, когда их станет больше, подумаем, как их стоит группировать и нужно ли вообще это.

2022-09-18 18:47 UTC, AntonZelinsky approved these changes
Я не имел в ввиде убирать переменную, я предлагагл объявлять её внутри переменной и использовтаь её в функции, но ладно... рас уже сделал так, то можно не поправлять

2022-09-19 08:21 UTC, petrovskydv commented
замечаний больше нет

2022-09-19 08:22 UTC, petrovskydv approved these changes

2022-09-19 08:33 UTC, merged